- fastrtps_cmake_module/package.xml
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
These changes made it compile for me with the latest versions of all other ROS 2 repos.
> update to new rmw error handling code, add explicit build type

- rmw_fastrtps_cpp/src/functions.cpp
This is necessary for the recent changes in ros2/rmw#28
> add domain id to node creation

- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
http://ci.ros2.org/job/ros2_batch_ci_osx/291/
> fix CMake syntax

- rmw_fastrtps_cpp/src/functions.cpp
This shouldn't be merged until https://github.com/ros2/rcl/pull/5 is merged.
This pull request will be needed once https://github.com/ros2/rmw/pull/48 gets merged.
> support the upcoming rmw changes from the rcl refactor

- rmw_fastrtps_cpp/src/functions.cpp
Fix for #7.
Before http://ci.ros2.org/view/nightly/job/nightly_linux/131/console#console-section-19
After
http://ci.ros2.org/job/ci_linux/807/
http://ci.ros2.org/job/ci_osx/673/
http://ci.ros2.org/job/ci_windows/859/
> add missing const

- rmw_fastrtps_cpp/src/functions.cpp
> Refactor for rmw_wait/rmw_waitset changes

- rmw_fastrtps_cpp/src/functions.cpp
> Don't type-erase request header

- rmw_fastrtps_cpp/src/functions.cpp
Before: http://ci.ros2.org/job/ci_osx/919/
After: http://ci.ros2.org/job/ci_osx/920/
> fix memory leak

- rmw_fastrtps_cpp/src/functions.cpp
> Remove fixed guard conditions

- rmw_fastrtps_cpp/src/functions.cpp
see explanation in ros2/rmw_connext#151
> Make identifier consistent

- rmw_fastrtps_cpp/src/functions.cpp
This time it only has one commit. Thanks Tully :smile:
> Explicit downcast to fix warning on Windows

- rmw_fastrtps_cpp/CMakeLists.txt
Connect to ament/ament_cmake#68
> use CTest BUILD_TESTING

- rmw_fastrtps_cpp/CMakeLists.txt
Added C++11 flag, like in https://github.com/ros2/rmw_opensplice/blob/master/rmw_opensplice_cpp/CMakeLists.txt#L5
Connects to https://github.com/ros2/rmw/pull/69
> Add C++11 flag

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
follow-up of #45 
The goal of this PR is to provide support for all ROS2 message types in rmw_fastrtps_cpp
> serialize deserialize arrays

- rmw_fastrtps_cpp/src/functions.cpp
This checks that the structure `topic_names_and_types` is properly initialized
needed for https://github.com/ros2/rclpy/pull/40
connects to https://github.com/ros2/rclpy/pull/40
> Error checking get names and types

- rmw_fastrtps_cpp/src/functions.cpp
WIP: moving rcl_topic_names_and_types structure sanity checks at the rcl level
connects to https://github.com/ros2/rcl/pull/85
> use rmw sanity check function

- rmw_fastrtps_cpp/src/functions.cpp
Needed to support https://github.com/ros2/rmw/pull/72.
Connects to ros2/rmw_connext#168
> pass node to client/service destroy functions

- fastrtps_cmake_module/CMakeLists.txt
- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
- fastrtps_cmake_module/package.xml
- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/impl/rmw/get_service_type_support_handle.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/impl/rmw/get_type_support_handle.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/macros.hpp
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=1862)](http://ci.ros2.org/job/ci_linux/1862/)
* OS X [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1397)](http://ci.ros2.org/job/ci_osx/1397/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=1780)](http://ci.ros2.org/job/ci_windows/1780/)
> update style and enable linters

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
Follow up of https://github.com/ros2/rmw_fastrtps_cpp/pull/65#issuecomment-257468482
> more static casts

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.h
Propagate TODO to make sure we implement the maxSize logic everywhere it's needed
connects to https://github.com/ros2/rmw_fastrtps/issues/72
> propagate TODO

- rmw_fastrtps_cpp/src/functions.cpp
This changes the parameters of the Publishers and Subscriber for service clients and server to match the regular pub/sub ones.
This fixes https://github.com/ros2/rmw_fastrtps/issues/70
Connects to https://github.com/ros2/rmw_fastrtps/issues/70
> Fix long req reply

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
> typesupport reloaded

- rmw_fastrtps_cpp/src/functions.cpp
Connects to https://github.com/ros2/rmw/issues/85
> Rename QoS policies

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
Connect to ros2/rosidl_typesupport#6
> use rosidl_typesupport_c

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
> remove dependency on rosidl_typesupport_*

- rmw_fastrtps_cpp/src/functions.cpp
> update to support node namespace in rmw API

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
> use string_array_t from c_utilities package

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
Connects to ros2/c_utilities#17
> rename {c_}utilities to rcutils

- rmw_fastrtps_cpp/src/functions.cpp
This builds on top of #108.
While this patch implements the necessary logic in `rmw_fastrtps_cpp` I never saw that the code path actually got triggered. @richiprosima Maybe you can shed some light into this. When should `onNewCacheChangeAdded` be invoked with a `kind` not equal to `ALIVE`? Currently I don't see it being invoked (hence topics / types are never removed despite calling `rmw_destroy_publisher`).
> support removing topics types

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/functions.cpp
connects to ros2/ros2#327
working implementation.
What's missing:
- Cleanup memory management in the style of: https://github.com/ros2/rmw_fastrtps/pull/97/commits/983ea01a2f488a31711a0b6dfefa1d358ecdc2ee
- Figure out why the two postfixes "Reply" and "Request" are necessary. Without these, the services won't match.
> namespace implementation

- rmw_fastrtps_cpp/src/functions.cpp
> fix removal of topics / types

- rmw_fastrtps_cpp/src/functions.cpp
> implement avoid_ros_namespace_conventions QoS option

- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
- rmw_fastrtps_cpp/CMakeLists.txt
Reverts ros2/rmw_fastrtps#75
See: https://github.com/ros2/rmw_fastrtps/pull/75#issuecomment-306731307
> Revert "Export FastRTPS libraries"

- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
- rmw_fastrtps_cpp/CMakeLists.txt
This should address the remaining issue of #75
> Look for debug versions of fastcdr and fastrtps as well

- rmw_fastrtps_cpp/src/functions.cpp
> add allocator to split function

- rmw_fastrtps_cpp/src/functions.cpp
> DDS Security support

- rmw_fastrtps_cpp/src/functions.cpp
> Refactor get topic names and types

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/src/functions.cpp
For consistency and to not confuse `cppcheck`.
Connects to ros2/ros2#368
> use hpp for c++ code

- rmw_fastrtps_cpp/src/functions.cpp
Fix the counting for the subscribers and publishers to a topic.
connects to #127
> Fix publisher/subscriber Count

- rmw_fastrtps_cpp/src/functions.cpp
Fixes ros2/ros2#376.
I know this might conflict with the refactoring @Karsten1987 is about to do (#131). If you haven't started the refactoring yet this could maybe be merged before. Otherwise since this patch is minimal I can easily rebase it afterwards.
> add missing mutex lock

- rmw_fastrtps_cpp/src/types/custom_client_info.hpp
- rmw_fastrtps_cpp/src/types/custom_service_info.hpp
Reapplies #132.
This time actually waiting for #131 to be done :wink:
> Reapply "add missing mutex lock""

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
connects to ros2/ros2#387
CI jobs are in the above issue
> Make sure to free memory associated with the service_name.

- rmw_fastrtps_cpp/src/rmw_node.cpp
Use rmw_allocate in place of malloc and rmw_free in place of free.
---
CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3163)](http://ci.ros2.org/job/ci_linux/3163/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=501)](http://ci.ros2.org/job/ci_linux-aarch64/501/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2520)](http://ci.ros2.org/job/ci_osx/2520/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3214)](http://ci.ros2.org/job/ci_windows/3214/)
> Use rmw_allocate/rmw_free

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/src/demangle.cpp
- rmw_fastrtps_cpp/src/qos.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_wait.cpp
Connect to ament/uncrustify#18.
> update style to match latest uncrustify

- rmw_fastrtps_cpp/src/rmw_wait.cpp
Closes https://github.com/ros2/rmw_connext/issues/260.
Bugfix, defensive programming.
> pointers are checked for null

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_cpp/src/client_service_common.cpp
- rmw_fastrtps_cpp/src/client_service_common.hpp
- rmw_fastrtps_cpp/src/get_client.cpp
- rmw_fastrtps_cpp/src/get_participant.cpp
- rmw_fastrtps_cpp/src/get_publisher.cpp
- rmw_fastrtps_cpp/src/get_service.cpp
- rmw_fastrtps_cpp/src/get_subscriber.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_count.cpp
- rmw_fastrtps_cpp/src/rmw_get_gid_for_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_cpp/src/rmw_service_server_is_available.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_topic_names_and_types.cpp
- rmw_fastrtps_cpp/src/rmw_trigger_guard_condition.cpp
- rmw_fastrtps_cpp/src/rmw_wait.cpp
- rmw_fastrtps_cpp/src/rmw_waitset.cpp
- rmw_fastrtps_cpp/src/types/guard_condition.hpp
This commit use auto to deduce complex TYPE and replace NULL with nullptr. It
helps to keep coding style consistent across the project
> use auto deduction and nullptr to keep coding style consistent

- rmw_fastrtps_cpp/package.xml
Connect to ros2/rmw_implementation#36.
> rename dependency group

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/rmw_fastrtps_cpp-extras.cmake
> change export order for static linking

- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
> use size_t

- rmw_fastrtps_cpp/src/rmw_node.cpp
> update usage of rcutils_join_path()

- fastrtps_cmake_module/package.xml
- rmw_fastrtps_cpp/package.xml
To be fast-forwarded onto master if approved.
> Prepare 0.5.0

- rmw_fastrtps_cpp/src/type_support_common.hpp
Connects to ament/uncrustify#24
> fix template closing indentation

- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
rebased version of #225 
Connects to ros2/sros2#67
@codebot FYI
> separating identity and permission CAs

- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
> use uint8_array

- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
This solves an issue on deserialization detected [here](https://ci.ros2.org/view/nightly/job/nightly_linux_extra_rmw_release/176/#showFailuresLink)
> Fixing failing tests on rmw_fastrtps_dynamic_cpp.

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
> Methods to retrieve matched counts on pub/sub

- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_cpp/src/rmw_wait_set.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_wait_set.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
> pass context to wait set and fini context

- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/topic_cache.hpp
- rmw_fastrtps_shared_cpp/package.xml
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/types/guard_condition.hpp
Depends on:
* https://github.com/ros2/rcpputils/pull/2
* https://github.com/ros2/ros2/pull/661
Related to https://github.com/ros2/ros2/issues/664
Depends on https://github.com/ros2/rcpputils/pull/6
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Thread safety annotation - minimally intrusive first pass

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
To enable unit testing from Python side
Unblocks ros2/rclpy#316
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Set more correct return values for unimplemented features (QoS)

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/names.hpp
- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
This is a work in progress 
This change is needed for rmw_fastrtps to be compatible with Fast-RTPS 1.8.0
depends on osrf/osrf_testing_tools_cpp#31
> Upgrades to support Fast-RTPS 1.8.0

- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
Signed-off-by: Robin Vanhove <rov@robopec.com>
> fix log_debug typo in rmw_count

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
onNewDataMessage() is called as a callback from Fast-RTPS when
there is new data.  When that happens, some locks inside of
Fast-RTPS are taken, followed by internalMutex_ in SubListener.
However, the rest of SubListener takes internalMutex_ first,
followed by calls into Fast-RTPS where locks are taken.  This
is an ABBA deadlock.  Break the deadlock by doing the calls
into Fast-RTPS before taking the internalMutex_.
This should fix #285 
@MiguelCompany @richiprosima Any thoughts on this?
> Fix ABBA deadlock.

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
Minor thing I noticed while doing something else.
Linux: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7328)](https://ci.ros2.org/job/ci_linux/7328/)
> Fix error message

- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/src/type_support_common.hpp
- rmw_fastrtps_shared_cpp/src/demangle.cpp
The rcpputils implementation is more performant.
Connects to https://github.com/ros2/rmw_fastrtps/issues/277
Requires https://github.com/ros2/rcpputils/pull/13
> Use rcpputils::find_and_replace instead of std::regex_replace

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
> Add missing lock guards for discovered_names and discovered_namespaces

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
Needed to support Fast-RTPS 1.9.0.
Connects to https://github.com/ros2/ros2/pull/747
> Support Fast-RTPS 1.9.0

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
Follow-up of https://github.com/ros2/rmw_fastrtps/pull/311/files, after reading the error messages reported in https://github.com/ros2/build_cop/issues/241.
> Correct error message

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
> [Dashing] Fix bug in graph API by node (#316)

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
> update signature for added pub/sub options

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Implements https://github.com/ros2/design/issues/259
Replaces https://github.com/ros2/rmw_fastrtps/pull/363 and https://github.com/ros2/rmw_fastrtps/pull/359 as discussed.
> Fill message_info timestamp

- rmw_fastrtps_dynamic_cpp/package.xml
> Fixed rmw_fastrtps_dynamic_cpp package description

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/test/test_dds_attributes_to_rmw_qos.cpp
See https://github.com/ros2/rmw/pull/227.
> Remove MANUAL_BY_NODE liveliness API

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Update QDs for 1.0

- rmw_fastrtps_shared_cpp/src/participant.cpp
Precisely what the title says. Connected to https://github.com/ros2/rcl/pull/689.
> Handle RMW_DEFAULT_DOMAIN_ID.

- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
Connected to https://github.com/ros2/rmw/pull/247.
> Amend rmw_init() implementation: require enclave.

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
Connected to https://github.com/ros2/rmw/pull/249.
> Ensure compliant node construction/destruction API.

- rmw_fastrtps_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
See https://github.com/ros2/rcl/pull/718
> Set context actual domain id

- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/src/subscription.cpp
Depends on https://github.com/ros2/rmw/pull/256.
> Ensure compliant subscription API.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
> [backport foxy] Fix trying to get topic data that was already removed

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
Connected to https://github.com/ros2/rmw/pull/262.
> Ensure compliant matched pub/sub count API.

- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
> Updated error returns on rmw_publish_serialize to comply with documentation

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_wait.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_wait.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
Updated return codes for unimplemented rmw_*_*_allocation functions. Related with this PR https://github.com/ros2/rmw_implementation/pull/137
> Updated rmw_* return codes

- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Checked client implementation and return RMW_RET_INCORRECT_RMW_IMPLEMENTATION
> Checked client implementation and return RMW_RET_INCORRECT_RMW_IMPLEMENTATION in rmw_service_server_is_available

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
- rmw_fastrtps_shared_cpp/src/publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_guard_condition.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
- rmw_fastrtps_shared_cpp/src/subscription.cpp
Precisely what the title says.
> Perform fault injection in all creation/destruction APIs.

- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_shared_cpp/package.xml
> Update maintainer list for Dashing

- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_shared_cpp/package.xml
> Update maintainer list for Eloquent

- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_shared_cpp/package.xml
> Update maintainer list for Foxy

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
There were actually 2 problems here:
1.  We were missing the lock in check_for_subscription()
completely (this is the original issue that caused me to
examine this code).
2.  We had an accessor for clients_endpoints_ so that external
users could get a reference.  But with that being the case,
any access to the returned reference would be without a lock.
Since we were only accessing client_endpoints_ in two places,
make some methods in ServicePubListener to do the requested
operations while holding the lock, getting rid of the problem.
Note that the patch here is slightly different than the one on master, since I had to take into account the ABI-compatible differences.  Like I did with master, I'm going to run a full CI on …
> [Foxy backport]: Make sure to lock the mutex protecting client_endpoints_. (#492)

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/rmw_qos.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_qos.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_qos.cpp
- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
- rmw_fastrtps_shared_cpp/test/test_qos_profile_check_compatible.cpp
Implements https://github.com/ros2/rmw/pull/299
Depends on https://github.com/ros2/rmw_dds_common/pull/45
> Add RMW function to check QoS compatibility

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_dynamic_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
> Updating Quality Declaration

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Signed-off-by: Jose Antonio Moral <joseantoniomoralparras@gmail.com>
> Support for SubscriptionOptions::ignore_local_publications

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Backporting #536 into Galactic
> [Galactic] Support for SubscriptionOptions::ignore_local_publications

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Equivalent to #543. targeting the correct branch.
> [galactic backport] Support for SubscriptionOptions::ignore_local_publications (#536)

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
> Add client/service QoS getters

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
Relates to https://github.com/ament/ament_lint/pull/324
> Fix cpplint error

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/CMakeLists.txt
Part of https://github.com/ros2/ros2/issues/1150 - this installs headers to a unique directory in a merged workspace.
> Install headers to include/${PROJECT_NAME}

- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
address https://ci.ros2.org/job/ci_windows/16757/msbuild/
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
> address linter waning for windows.

- rmw_fastrtps_dynamic_cpp/src/rmw_features.cpp
Minor problem detected while processing #600
> Fix cpplint error on master

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
This reverts commit 7202ceb7e379ec0fbcaf895cfcef6983ddcc7077.
Signed-off-by: Tomoya Fujita <Tomoya.Fujita@sony.com>
> Revert "add line feed for RCUTILS_SAFE_FWRITE_TO_STDERR (#608)"

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/rmw_get_gid_for_client.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_get_gid_for_client.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_get_gid_for_client.cpp
See: https://github.com/ros2/rmw/pull/327
Signed-off-by: Brian Chen <brian.chen@openrobotics.org>
> Add rmw_get_gid_for_client impl

- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
This PR resolves (#647)
Signed-off-by: Wooyoung Choi <wy.choi@naverlabs.com>
> Fix incoherent dissociate_writer to dissociate_reader (#647)

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
Part of ros2/ros2#1159
Depends on ros2/rosidl#727 (and is bundled with)
> Use get_type_hash_func on typesupports (rep2011)

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_event_info.hpp
address https://github.com/ros2/rmw_fastrtps/issues/688
> address clang nightly build error.

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/CMakeLists.txt
address https://github.com/ros2/rmw_fastrtps/issues/700
> fastdds version update into 2.6.2 for humble

- README.md
> add doc section for Zero Copy Data Sharing.

- README.md
#718 introduced documentation for enabling Zero Copy comms. This PR clarifies some points of that documentation.
> Clarify Data Sharing enabling

- README.md
> a couple of minor doc updatse.

- rmw_fastrtps_dynamic_cpp/src/type_support_common.cpp
address https://github.com/ros2/rmw_fastrtps/issues/742
> compare string contents but string pointer addresses.

- rmw_fastrtps_shared_cpp/src/rmw_init.cpp
comes with https://github.com/ros2/rcl/pull/1169
> remove rmw_localhost_only_t.
