- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport.h
- rmw_fastrtps_cpp/src/functions.cpp
One thing I had to do was disable the find_package(fastrtps) call.
This is because the CMake module for Fast-RTPS is incomplete:
https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/master/fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake#L48
This results in a syntax error from CMake.
It happens to compile even without the find_package rule, so I disabled it for now.
However, it should really be finished and added back to this CMake logic.
> A few small changes to get it building on my system.

- fastrtps_cmake_module/CMakeLists.txt
- fastrtps_cmake_module/package.xml
- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
This will fix the failing linter tests in the `rmw_fastrtps_cpp` package (http://ci.ros2.org/job/ros2_batch_ci_linux/389/testReport/).
> remove all linters but cppcheck

- rmw_fastrtps_cpp/package.xml
Since we build each package in isolation now failing to declare the correct dependencies won't make them available to this package.
> fix declared dependencies

- rmw_fastrtps_cpp/src/functions.cpp
This test result:
http://ci.ros2.org/view/nightly/job/nightly_linux/143/testReport/%28root%29/test_services_cpp__rmw_fastrtps_cpp/test_services_cpp/
shows a service client crashing with a SIGABRT (-6). valgrind identified mismatched allocation and destruction calls. Here I'm matching them up. With this change, valgrind gives a zero-error report on the service client (there still seem to be situations in which the test can hang instead of passing, but that's a different matter).
> Match alloc and free calls

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
`rmw` is listed as an exported dependency in CMake (https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/blob/7631ef13594cdd7badd40d3d5c4d5d478ec9bd48/rmw_fastrtps_cpp/CMakeLists.txt#L16) but not listed in the package.xml.
Failing job: http://ci.ros2.org/job/ci_windows/933/consoleFull#console-section-66
Fixed in http://ci.ros2.org/job/ci_windows/935/
> fix missing export dependency

- rmw_fastrtps_cpp/package.xml
Fix regression of #13 unbreaking the CI build.
Before: http://ci.ros2.org/job/ci_linux/919/ and http://ci.ros2.org/view/nightly/job/nightly_linux/185/
After: http://ci.ros2.org/job/ci_linux/924/
> add missing dep on introspection c

- rmw_fastrtps_cpp/src/MessageTypeSupport.cpp
Avoid Windows compiler warning by making the 64->32 bit downcast explicit.
> Explicit downcast of type size

- rmw_fastrtps_cpp/CMakeLists.txt
With only FastRTPS several examples fail to link since it seems to use `pthread` but doesn't export it (at least on Xenial, maybe also with other RMW impl. but currently I only have FastRTPS).
* http://ci.ros2.org/job/ci_linux/1159/
* http://ci.ros2.org/job/ci_osx/937/
* http://ci.ros2.org/job/ci_windows/1215/
> export pthread dependency

- rmw_fastrtps_cpp/src/MessageTypeSupport.cpp
- rmw_fastrtps_cpp/src/ServiceTypeSupport.cpp
Unfortunately Windows throws a compiler warning when it sees strdup(); it wants to see _strdup() instead.
> Fix memory leak on Windows

- rmw_fastrtps_cpp/CMakeLists.txt
Connects to ros2/rmw#63
New usage of `register_typesupport_implementation` to specify language of the typesupport packages. Once C is added, introspection_c will need to be added to this macro call.
> Register language of typesupport packages

- rmw_fastrtps_cpp/src/functions.cpp
This is needed so that rcl can compile. All the code which uses this downstream is configured to not test this code (which just raises 'not implemented').
Connects to ros2/ros2#215
> stub functions for wait_for_service

- rmw_fastrtps_cpp/src/functions.cpp
Previously it was just returning junk, which was left over from my `wait_for_service` work.
This doesn't implement it, but at least it returns a valid guard condition. I wouldn't return anything at all, but `rcl_node_init` calls it, so I have to return something valid or else all fastrtps programs would fail.
> fix rmw_get_graph_guard_condition

- rmw_fastrtps_cpp/src/TypeSupport.cpp
- rmw_fastrtps_cpp/src/functions.cpp
See http://ci.ros2.org/job/ci_windows/1395/warnings34Result/fixed/
No regressions on the other platforms:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=1383)](http://ci.ros2.org/job/ci_linux/1383/)
* OS X [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=1080)](http://ci.ros2.org/job/ci_osx/1080/)
See related changes eProsima/Fast-RTPS#43
> fix warnings on Windows

- rmw_fastrtps_cpp/src/TypeSupport.cpp
Linux:
* before: http://ci.ros2.org/job/ci_linux/1390/testReport/
* after: http://ci.ros2.org/job/ci_linux/1391/testReport/
* -16 failing tests
OS X:
* before: http://ci.ros2.org/job/ci_osx/1085/testReport/
* after: http://ci.ros2.org/job/ci_osx/1086/testReport/
* -13 failing tests
The uninitialized values should be addressed too but they are coming from our code, e.g. `rclcpp::ParameterVariant`.
> make serialization of bool values more robust against uninitialized values

- rmw_fastrtps_cpp/src/TypeSupport.cpp
unary minus on an unsigned int gives a compiler warning in windows.
> fix compiler warning on windows

- rmw_fastrtps_cpp/src/functions.cpp
@dirk-thomas It solves the communication error between OpenSplice and FastRTPS using
localhost interface on Mac OSX. For an unknown reason, OpenSplice doesn't response our ACKs when our participant has the lease duration set to infinitive.
> Participant lease duration set to default.

- rmw_fastrtps_cpp/src/functions.cpp
- Fixes issue with qos settings not applying in rmw_fastrtps_cpp (at all)
> Attributes are now correctly passed by reference in rmw_fastrtps_cpp

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
@jacquelinekay I noticed that the universal reference was removed when https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/pull/27 was merged, I don't know if it was causing any issues on the buildfarm, I checked locally and it seems to work fine.
Alternatively, I also pushed #50, which accomplishes the same but without using universal references, in case the universal reference were causing trouble.
> Use a universal reference to avoid extra std::string copies

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.h
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
- rmw_fastrtps_cpp/src/functions.cpp
Replacement for #47 and closes #36.
I tested this and it seems to work as expected, with the caveats about OS X mentioned in https://github.com/eProsima/ROS-RMW-Fast-RTPS-cpp/issues/36#issuecomment-229718748.
This requires my FastCDR branch (https://github.com/eProsima/Fast-CDR/pull/7) and the feature branch of Fast-RTPS (https://github.com/eProsima/Fast-RTPS/tree/feature/dynamicmemory_revision) for which there is no pull request yet.
> Large message pub sub revision

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
This PR serializes and deserializes unbounded arrays. Tested locally with two Python scripts (listener and talker), using different permutations of OpenSplice and FastRTPS.
> Serialize and deserialize arrays

- rmw_fastrtps_cpp/src/functions.cpp
This PR contains the service_is_available functionality. To work properly Fast-RTPS has to be in/after commit eProsima/Fast-RTPS@24825bb0de6cc5fdf16949a350c40570f2b00f26. 
Closes #14.
> Added new functionality: service_is_available

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
Fixes #60.
Before:
* http://ci.ros2.org/job/ci_linux/1776/
* http://ci.ros2.org/job/ci_osx/1344/
* http://ci.ros2.org/job/ci_windows/1704/
After:
* http://ci.ros2.org/job/ci_linux/1777/
* http://ci.ros2.org/job/ci_osx/1345/
* http://ci.ros2.org/job/ci_windows/1705/
> do not artifically limit maximum string length

- rmw_fastrtps_cpp/src/functions.cpp
This will unify the symbols across the type support packages so that they only differ in the namespace.
Connect to ros2/rosidl_typesupport#1.
> unify identifier naming

- rmw_fastrtps_cpp/src/functions.cpp
> expose list of nodes

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
- rmw_fastrtps_cpp/src/functions.cpp
In future version of Fast RTPS, CDR encapsulation has to be done outside of the fastrtps library. This PR implements the CDR encapsulation on rmw_fastrtps_cpp.
> Added CDR encapsulation

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
>  Downgrade casts to support mapping ROS char into C signed char

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.h
- rmw_fastrtps_cpp/src/functions.cpp
This cherry picks a330d0e from the sros2 branch (with a style fixup) at the suggestion of @mikaelarguedas in order to support the current master branch of eProsima/Fast-RTPS.
Combined with https://github.com/ros2/ros2/pull/332 this will enable the update of Fast-RTPS to upstream's master once some local CMake changes are accepted upstream.
> Cherry pick sros2 update for Fast-RTPS master support

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
@Karsten1987 with this change to https://github.com/ros2/rmw_fastrtps/pull/100 I can use that PR and the associated branches to test a fix for https://github.com/ros2/build_cop/issues/12 (Currently the jobs fail otherwise: http://ci.ros2.org/job/ci_linux/2516).
> Complete the switch to rcutils for PR 100

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
This PR delegates the decision to build a shared or a static library to CMake's BUILD_SHARED_LIBS
Update:
Connects to https://github.com/ros2/ros2/issues/306
> Control shared/static linking via BUILD_SHARED_LIBS and ament_cmake_ros

- rmw_fastrtps_cpp/src/functions.cpp
The problematic `delete` line was moved above the block which destroys the guard condition in https://github.com/ros2/rmw_fastrtps/commit/181265638dac5253d45816a1d3bb652603244e7f#diff-8225b098f1ec4debcdcee03d65ae95d5R771
Before: http://ci.ros2.org/job/ci_windows/2693/testReport/
After: http://ci.ros2.org/job/ci_windows/2694/testReport/
Fixes ros2/build_cop#19
> fix usage of deleted memory introduced in #97

- rmw_fastrtps_cpp/src/functions.cpp
As a result of #51 the guard condition was constantly been triggered since `onNewCacheChangeAdded` is being invoked repeatedly for the same topic / type.
[![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2598)](http://ci.ros2.org/job/ci_linux/2598/) using `--retest-until-fail 20` (all failing tests are also present in the corresponding nighlty)
Ready for review.
> fix unnecessary wake ups

- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
Replaces #91. Fixes #90.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2613)](http://ci.ros2.org/job/ci_linux/2613/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=186)](http://ci.ros2.org/job/ci_linux-aarch64/186/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2069)](http://ci.ros2.org/job/ci_osx/2069/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2726)](http://ci.ros2.org/job/ci_windows/2726/)
> remove obsolete stuff from CMake module

- rmw_fastrtps_cpp/src/functions.cpp
this should fix the inconsistency with `rclcpp::Node::count_subscribers` and `rclcpp::Node::count_publishers` as well as `get_topic_names_and_types`.
The function truncates the internal topic fqdn in the form of `rt/my_namespace/my_topic` into `/my_namespace/my_topic`
@clalancette Could you please review this and report whether this solves your issue?
> Topic names

- fastrtps_cmake_module/cmake/Modules/FindFastRTPS.cmake
- rmw_fastrtps_cpp/CMakeLists.txt
This PR ensures that the FastRTPS and FastCDR libraries are exported to downstream packages.
Tested on OSX, before:
```sh
$ otool -L install_isolated/rclcpp_examples/bin/talker__rmw_fastrtps_cpp
install_isolated/rclcpp_examples/bin/talker__rmw_fastrtps_cpp:
@rpath/librclcpp.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/librcl.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/librcl_interfaces__rosidl_typesupport_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/librcl_interfaces__rosidl_typesupport_introspection_cpp.dylib (compatibility version 0.0.0, current version 0.0.0)
@rpath/librcl_interfaces__rosidl_generator_c.dylib (compatibility version 0.0.0, current version 0.0.0) …
```
> Export FastRTPS libraries

- rmw_fastrtps_cpp/src/functions.cpp
This has two rather small changes. 
1) strings are now allocated for the topic name with `rmw_allocate` and freed with `rmw_free`.
2) publisher and subscriber objects are freed using their respective free functions.
connects to ros2/rmw_fastrtps#107
> Properly clean up publisher/subscriber topic_name

- rmw_fastrtps_cpp/src/functions.cpp
In newer versions of GCC, a compiler warning appears when you catch a polymorphic type by value.
```
Scanning dependencies of target rmw_fastrtps_cpp
[ 50%] Building CXX object CMakeFiles/rmw_fastrtps_cpp.dir/src/functions.cpp.o
/home/allenh1/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/functions.cpp: In function ‘rmw_node_t* create_node(const char*, const char*, eprosima::fastrtps::ParticipantAttributes)’:
/home/allenh1/ros2_ws/src/ros2/rmw_fastrtps/rmw_fastrtps_cpp/src/functions.cpp:841:17: warning: catching polymorphic type ‘class std::bad_alloc’ by value [-Wcatch-value=]
} catch (std::bad_alloc) {
^~~~~~~~~
```
The fix is to catch a reference (or a pointer). I personally don't understand why it is _bad_ to catch a polymorphic type by value (I guess it could be bad if your …
> Fix Compiler Warning

- rmw_fastrtps_cpp/src/functions.cpp
When calling the constructor without any arguments the pointer of the allocated buffer is later overwritten and therefore leaked: https://github.com/eProsima/Fast-RTPS/blob/f16b8f365c44aa76066b35004e84e9a352949d8c/include/fastrtps/rtps/common/CDRMessage_t.h#L53
Calling the constructor with the size argument `0` ensures that no memory is being allocated within the constructor.
> fix memory leak

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
Depends on ros2/rosidl#223.
This fixes the memory problems described in ros2/system_tests#211 for me. @mikaelarguedas It would be great if you can try to reproduce the result against the branch of the referenced PR. @Kukanani It would be great if you could try your demo with these two patches again.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2817)](http://ci.ros2.org/job/ci_linux/2817/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=324)](http://ci.ros2.org/job/ci_linux-aarch64/324/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2276)](http://ci.ros2.org/job/ci_osx/2276/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2956)](http://ci.ro …
> using sizeof provided by introspection

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/rmw_fastrtps_cpp-extras.cmake
This was exporting absolute library paths which made the generated CMake config files not relocatable. ~~Since the export isn't necessary this patch just removes it.~~
* ~~Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2834)](http://ci.ros2.org/job/ci_linux/2834/)~~
* ~~Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=338)](http://ci.ros2.org/job/ci_linux-aarch64/338/) (aborted since parallel build hung)~~
* ~~macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2290)](http://ci.ros2.org/job/ci_osx/2290/)~~
* ~~Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2970)](http://ci.ros2.org/job/ci_windows/2970/)~~
Ready for review.
> move export of FastRTPS libraries to extra file to avoid hardcoded absolute paths

- rmw_fastrtps_cpp/package.xml
Fixing regression of #128.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=2841)](http://ci.ros2.org/job/ci_linux/2841/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=345)](http://ci.ros2.org/job/ci_linux-aarch64/345/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2297)](http://ci.ros2.org/job/ci_osx/2297/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=2978)](http://ci.ros2.org/job/ci_windows/2978/)
> add missing build export dep

- rmw_fastrtps_cpp/src/functions.cpp
Reverts ros2/rmw_fastrtps#132 to make #131 easier.
Will reapply this patch afterwards.
> Revert "add missing mutex lock"

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_publisher_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/get_client.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/get_publisher.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/get_service.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/get_subscriber.hpp
- rmw_fastrtps_cpp/src/get_client.cpp
- rmw_fastrtps_cpp/src/get_publisher.cpp
- rmw_fastrtps_cpp/src/get_service.cpp
- rmw_fastrtps_cpp/src/get_subscriber.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_get_gid_for_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_service_server_is_available.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_cpp/src/rmw_wait.cpp
Follow up of #145 additionally exposing the publishers and subscribers of topics as well as services.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3058)](http://ci.ros2.org/job/ci_linux/3058/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=451)](http://ci.ros2.org/job/ci_linux-aarch64/451/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2457)](http://ci.ros2.org/job/ci_osx/2457/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3129)](http://ci.ros2.org/job/ci_windows/3129/)
> Expose more native handles

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_cpp/src/rmw_wait.cpp
- rmw_fastrtps_cpp/src/types/guard_condition.hpp
@dhood and I have been looking at the deadlocks some more together and finally figured out that https://github.com/ros2/rmw_fastrtps/pull/132#discussion_r134360020 introduced a regression (more details there).
Hopefully this patch will cover #142 as well a #143.
:clap: goes to @dhood for figuring out all these cases and working on the fixes.
> fix listener locking

- rmw_fastrtps_cpp/rmw_fastrtps_cpp-extras.cmake
Without this patch the exported `rmw_fastrtps_cpp_LIBRARIES` can't be used on Windows to link another target against FastRTPS. `rmw_fastrtps_cpp` itself doesn't use `FastRTPS_LIBRARIES` but links against the imported targets instead. Since this works this patch changes the exported libraries to contain the same. This will allow downstream packages to use `rmw_fastrtps_cpp` as intended.
Connect to ros2/demos#164.
Ready for review.
> export the imported targets

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
This is still in progress, but opening this for visibility.
connects to #72
> Clean up Magic Numbers

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
This PR removes old maximum lengths used when only preallocated memory policy was supported by FastRTPS.
Connects to #72
> Removing magic numbers: old maximun lengths

- rmw_fastrtps_cpp/CMakeLists.txt
src/rmw_init.cpp appear twice in add_library(rmw_fastrtps_cpp, ...). Drop the duplicated one.
> Drop duplicated rmw_init.cpp in rmw_fastrtps_cpp/CMakeLists.txt

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
Add support to get Fast RTPS configuration from a default XML file.
When running a ROS2 executable, if exists the XML file ``DEFAULT_FASTRTPS_PROFILES.xml`` in the execution directory then FastRTPS will load it and use the profiles defined with ``is_default_profile=true`` as default values for entity attributes.
With this PR, ROS2 will take the default values (maybe changed by and XML file) and then apply the ROS2 QoS profiles. A user shall be able to change attributes like ``heartbeatPeriod`` through an XML file.
> Support loading default XML profile file

- rmw_fastrtps_cpp/src/rmw_wait.cpp
Avoids the data having been already cleared for guard conditions
fixes the test added in ros2/rcl#169
CI of all repos including the new test added in ros2/rcl#169
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3354)](http://ci.ros2.org/job/ci_linux/3354/) (fixed the test: http://ci.ros2.org/job/ci_linux/3354/testReport/(root)/WaitSetTestFixture__rmw_fastrtps_cpp/zero_timeout_triggered_guard_condition/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=613)](http://ci.ros2.org/job/ci_linux-aarch64/613/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2691)](http://ci.ros2.org/job/ci_osx/2691/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3414)]( …
> Move the hasData checks for non-blocking wait 'timeout' higher

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
In https://github.com/ros2/rmw_fastrtps/issues/159 we realised this isn't actually used
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3364)](http://ci.ros2.org/job/ci_linux/3364/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=619)](http://ci.ros2.org/job/ci_linux-aarch64/619/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=2697)](http://ci.ros2.org/job/ci_osx/2697/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3421)](http://ci.ros2.org/job/ci_windows/3421/)
> Remove unnecessary dependency on rosidl_generator_cpp

- rmw_fastrtps_cpp/src/rmw_count.cpp
Addresses https://github.com/ros2/rmw_fastrtps/issues/166
> Remove string allocation in the count of subscribers and publishers

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
Dead code in API `rmw_create_subscription()`
becasue the condition "`rmw_subscription`" cannot be true in the
"`fail`" clauses, the execution cannot reach this statement:
`rmw_subscription_free(rmw_subscription);
`
finally, the "`rmw_subscribtion`" is free by
`rmw_destroy_subscription()` when it's not a nullptr
Dead code in API rmw_create_publisher()
because the condition "`rmw_publisher`" cannot be true in the
"`fail`" clauses, the execution cannot reach this statement:
`rmw_publisher_free(rmw_publisher);
`
finally, the "`rmw_publisher`" is free by
`rmw_destroy_publisher()` when it's not a nullptr
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>
> Fix rmw_fastrtps dead code

- rmw_fastrtps_cpp/src/rmw_client.cpp
_Issue_: the `info` in `fail` is always non-nullptr
_issue_: no checking to memory allocation of `rmw_client`, which
may leads to free `nullptr` in the following code:
`  rmw_client_free(rmw_client);`
_Issue_: uninteded memory free from `rmw_client->service_name`:
```
if (rmw_client->service_name != nullptr) {
rmw_free(const_cast<char *>(rmw_client->service_name));
rmw_client->service_name = nullptr;
}
```
when the code goes to `fail` before it's actually allocated here:
```
rmw_client->service_name = reinterpret_cast<const char *>(
rmw_allocate(strlen(service_name) + 1));
```
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>
> Fix the issues to dereference to nullptr

- rmw_fastrtps_cpp/src/rmw_node.cpp
Failing to save or free storage allocated from
`rcutils_join_path()`, which results in memory leak
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>
> memory leak issue

- rmw_fastrtps_cpp/src/rmw_node.cpp
Thus, we no longer need to cast away the const when freeing it.
connects to ros2/ros2#423
> rcutils_join_path returns a char * now.

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
For most type_id, there is no difference for serialization which can be unified in a common template function. However, for bool and string, there is extra check or logic for normal but array does not. Although it is weird, this commit keep the logic intact.
Signed-off-by: jwang <jing.j.wang@intel.com>
> Unify and simplify de/serializeROSmessage processing

- rmw_fastrtps_cpp/package.xml
Connect to ament/ament_package#63
> use format 3

- rmw_fastrtps_cpp/CMakeLists.txt
This doesnt seem to be necessary anymore and may fix some cross-compilation issues we are facing.
This is a manual revert of #24 
Linux job with only fastrtps
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3552)](http://ci.ros2.org/job/ci_linux/3552/)
> Don;t export pthread anymore

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp
This fixes ros2/rclcpp#280 and requires the recent API extension from eProsima/Fast-RTPS#166.
The following set of builds only shows that it doesn't introduce a regression but doesn't prove that it actually addresses the problem:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3733)](http://ci.ros2.org/job/ci_linux/3733/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=888)](http://ci.ros2.org/job/ci_linux-aarch64/888/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3071)](http://ci.ros2.org/job/ci_osx/3071/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=3830)](http://ci.ros2.org/job/ci_windows/3830/)
Connect to ros2/rclcpp#280.
> use newly exposed unread-count to avoid getting out-of-sync

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
`getEDPReaders` is possible to return `nullptr`
Signed-off-by: Ethan Gao <ethan.gao@linux.intel.com>
> Segmentation error to dereference nullptr

- rmw_fastrtps_cpp/src/demangle.cpp
- rmw_fastrtps_cpp/src/namespace_prefix.cpp
- rmw_fastrtps_cpp/src/namespace_prefix.hpp
- rmw_fastrtps_cpp/src/rmw_count.cpp
Address small performance issues to ROS2 impacting the `rmw_count_publishers` and `rmw_count_subscribers` method when called with a significante number of topics to count.
The root of the performance issues come from the duplication of `std::string` type of objects. These duplication are honerous with strings and cause a significante amount of CPU cycle to be wasted duplicating things.
> Small performance improvments

- rmw_fastrtps_cpp/src/rmw_wait.cpp
There is already function check_wait_set_for_data over there which can
help judge hasToWait, no need duplicated check one by one.
The logic is hasToWait = false if hasData is true, otherwise
keep hasToWait as it was.
Signed-off-by: jwang <jing.j.wang@intel.com>
> use existing check_wait_set_for_data to avoid duplicated code

- rmw_fastrtps_cpp/src/rmw_wait.cpp
Under the condition that "hasToWait && wait_timeout", there is no need to re-calc hasData to judge timeout because predicate already include the logic. We only need do it if hasToWait && !wait_timeout. This commit optimize timeout judgement which slightly improve the performance in some conditions
Signed-off-by: jwang <jing.j.wang@intel.com>
> optimize timeout judgement according to different condition

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_participant_info.hpp
- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_node_names.cpp
Connect to ros2/ros2#438.
Requires eProsima/Fast-RTPS@adb00149b8e60e152d1091b58674c5ae7fd8ad22
> Node name in user data

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_participant_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/reader_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/writer_info.hpp
- rmw_fastrtps_cpp/src/assign_partitions.hpp
- rmw_fastrtps_cpp/src/demangle.cpp
- rmw_fastrtps_cpp/src/qos.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_service_server_is_available.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
WIP: While this compile and passes all tests on Linux, it still needs some cosmetic style fixes so I'm leaving it in progress for now
See https://github.com/ros2/rmw_fastrtps/pull/195 for context
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4221)](http://ci.ros2.org/job/ci_linux/4221/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1265)](http://ci.ros2.org/job/ci_linux-aarch64/1265/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3493)](http://ci.ros2.org/job/ci_osx/3493/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4326)](http://ci.ros2.org/job/ci_windows/4326/)
> Fix namespaces

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
This should fix the segfaults that we were seeing on Bionic with rclcpp.
Connects to ros2/rclcpp#464
> Fix deserialization segfault in bionic.

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
eProsima change only
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4289)](http://ci.ros2.org/job/ci_linux/4289/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1294)](http://ci.ros2.org/job/ci_linux-aarch64/1294/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3522)](http://ci.ros2.org/job/ci_osx/3522/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=4371)](http://ci.ros2.org/job/ci_windows/4371/)
sros2 and rmw_fastrtps changes as well
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4296)](http://ci.ros2.org/job/ci_linux/4296/)
* Linux-aarch64 [![Build …
> Support access control 

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/rmw_fastrtps_cpp-extras.cmake
Reverts ros2/rmw_fastrtps#198
This made the artifacts not relocatable. 
Confirmed locally that reverting this change in the generated cmake-extras file make overlay work again.
See https://github.com/ros2/ci/issues/157#issuecomment-386966659 for more details
@sloretz FYI
Packaging job: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_packaging_linux&build=93)](https://ci.ros2.org/job/ci_packaging_linux/93/)
> Revert "Export rmw_fastrtps_cpp target"

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
This fixes a leak exposed by the `rclcpp` test `test_time_source`. A buffer is created on the heap, but it is only freed if someone takes the response. This PR uses an `std::unique_ptr` instead of a raw pointer to let RAII free the buffer if an error occurs or the listener is destroyed without taking a response.
CI
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4413)](http://ci.ros2.org/job/ci_linux/4413/)
* False positive cmake warning ros2/build_cop#79
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=1361)](http://ci.ros2.org/job/ci_linux-aarch64/1361/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=3606)](http://ci.ros2.org/job/ci_osx/3606/)
* Windows [![Build …
> Fix leak if client reponse is never taken

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/macros.hpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.hpp
> Expose raw CDR stream for publish and subscribe

- rmw_fastrtps_cpp/src/rmw_request.cpp
instantiate class Cdr
Before we are going to instantiate the fastcdr::Cdr class by using the member
variable buffer_ of class CustomServiceRequest, we must ensure that the buffer_
can not be nullptr.
This patch implements the validation.
Fix #209
> Validate the buffer_ of CustomServiceRequest object before using it to

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.hpp
This PR includes the necessary changes to remove the temporary buffer used on (de)serialization of messages, but keeping only the introspection typesupport.
I am still performing tests locally, but I have started the PR so others can perform their own tests, and check how it compares to #203
> Temporary buffer remove

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_client_info.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/custom_service_info.hpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_request.cpp
- rmw_fastrtps_cpp/src/rmw_response.cpp
- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.cpp
- rmw_fastrtps_cpp/src/ros_message_serialization.hpp
This is an improvement over #207 that removes allocations on more cases, including rmw_serialize.
I am rebasing #203 on top of this one, so if this one gets merged the other will be easier to review and merge.
It is passing the tests locally, so I hope it can make it into bouncy
> Avoid allocations

- rmw_fastrtps_shared_cpp/src/namespace_prefix.cpp
- rmw_fastrtps_shared_cpp/src/namespace_prefix.hpp
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
Change the runtime performance of `rmw_count_subscribers` and `rmw_count_publishers` to be O(logN) instead of linear.
connects to ros2/rmw_fastrtps#216
> Improve runtime performance of the `rmw_count_XXX` functions.

- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
This makes use of the [newly exposed](https://github.com/eProsima/Fast-RTPS/issues/213#issuecomment-407300333) memory strategy for builtins.
This should avoid issues like
```
[RTPS_HISTORY Error] Change payload size of 'XXXX' bytes is larger than the history payload size of '5000' bytes and cannot be resized. -> Function add_change
```
I'm currently unable to reproduce the original issue but I think that we still want to integrate this change to avoid corner cases where we get large discovery messages.
I didnt revert https://github.com/ros2/rmw_connext/pull/288 as it seems that we don't want to send TypeCode regardless of this change.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=4980)](http://ci.ros2.org/job/ci_linux/4980/)
* Linux-aarch64 [![Build …
> allow builtin reader/writer to reallocate memory if needed

- rmw_fastrtps_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp
> Include node namespaces in get_node_names

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/demangle.cpp
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
Connects to https://github.com/ros2/rcutils/issues/113
> Add semicolons to all RCLCPP and RCUTILS macros.

- rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
> use new error handling API from rcutils

- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/macros.hpp
> rename dynamic array to sequence

- rmw_fastrtps_cpp/src/rmw_guard_condition.cpp
- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_guard_condition.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
> refactor to support init options and context

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
We have implemented a new feature to apply the RMW configuration only from XML files, avoiding the current configuration set by code. To do that, rmw_fastrtps checks an environment variable called `RMW_FASTRTPS_LEAVE_MIDDLEWARE_DEFAULT_QOS`
Connects to ros2/ros2#589
> RMW_FastRTPS configuration from XML only

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/topic_cache.hpp
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
* Add topic cache object to maintain participant relationship
* Separate responsibility of maintaining cached data from listener
* Use lock_guard over manual mutex lock
* Use c++14 functions to reduce code
* Add debug statements
* Add lookup of topics for input node
* Remove unnecessary logging
* Add namespace to graph functions
> Add topic cache object for managing topic relations

- rmw_fastrtps_shared_cpp/src/types/guard_condition.hpp
1. ret is set as false at line 75 in thread A
2. hasTriggered_ is set as true at line 42 or 46 in thread B
3. hasTriggered_ is set as false at line 76 in thread A
In that case, guard condition triggered information is gone.
So, line 75, 76 codes MUST be thread synchronized with line 42 code.
> Fix guard condition trigger error

- rmw_fastrtps_shared_cpp/src/demangle.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
* rmw_fastrtps_shared_cpp/src/demangle.cpp:
* rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp:
* rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp:
> Use empty() to check for an empty string

- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
Follow up from #238.
Resolves #253
> Add missing logic to dynamic RMW client implementation

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
Found while compiling rmw_fastrtps against a newer version of Fast-RTPS, which apparently moved around which C++ standard headers they are exporting in their public headers.
> Make sure to include the C++ headers used by these headers.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Hopefully resolved the permanent failure from ros2/build_cop#166. The test is still flaky though and won't address ros2/build_cop#155.
> update listener logic for accurate counting

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
Error introduced in #262.
CI before: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6450)](https://ci.ros2.org/job/ci_linux/6450/)
CI after: [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=6452)](https://ci.ros2.org/job/ci_linux/6452/)
> Fix cpplint error

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
This PR fixes #258.
Internal Fast-RTPS counter and rmw_fastrtps `data_` counter can get out of sync if Fast-RTPS receives a new sample after rmw_fastrtps takes a sample and before it decreases `data_` counter.
The solution I provide is having the real count in the internal Fast-RTPS counter and `data_` always will get this information.
> Fixed race condition between taking sample and updating counter.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
This PR backports commits ea4fb7cfaa671a2118a7d54203c786d890d8ed38 and fc4b27e899efb91455de8863df2dbdd3887897f2 (PRs #256 and #264, respectively) into Crystal.  These are needed as part of the fixes to bring Fast-RTPS up to version 1.7.2.  Note that these have to go in *before* the update to v1.7.2, otherwise this will fail to build.  A full CI run for these changes was run as part of https://github.com/ros2/ros2/issues/669#issuecomment-475014351 .  @nuclearsandwich FYI
> Crystal backports

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
Implements api added in https://github.com/ros2/rmw/pull/169
Connects to ros2/rmw#169
> Add function to get publisher actual qos settings

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
When logging a rcutils_error_string_t variable, the
str field of the rcutils_error_string_t variable needs
to be logged, not the struct directly.
Signed-off-by: Thomas Moulard <tmoulard@amazon.com>
> Fix logging in rmw_node_info_and_types.cpp

- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publish.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Stubs out the expanded API, which isn't used in FastRTPS currently
Connects to ros2/rmw#159
> Updates for preallocation API.

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_cpp/src/type_support_common.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_common.hpp
- rmw_fastrtps_shared_cpp/src/demangle.cpp
Connects to ros2/ros2#677
---
TODO:
>  Support arbitrary message namespaces 

- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/package.xml
Closes ros2/build_cop#190.
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=7107)](http://ci.ros2.org/job/ci_linux/7107/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=3327)](http://ci.ros2.org/job/ci_linux-aarch64/3327/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=5822)](http://ci.ros2.org/job/ci_osx/5822/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=6927)](http://ci.ros2.org/job/ci_windows/6927/)
> add support for WString in rmw_fastrtps_dynamic_cpp

- rmw_fastrtps_shared_cpp/src/qos.cpp
When we first implemented QoS event support for Fast-RTPS 1.8, we were under the impression that AUTOMATIC Liveliness callbacks would be supported in the release, but this turned out to not be the case.
Fixes https://github.com/ros2/demos/issues/351
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Disable all liveliness until it is actually supported

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
Probably fixes #281
Signed-off-by: Miguel Company <miguelcompany@eprosima.com>
> Fixing data race on custom_participant_info.

- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
The current implementation of `get_actual_qos()` is not setting/output the values for lifespan, deadline, and liveliness QoS policies.
Depends on https://github.com/ros2/rmw/pull/175.
> get_actual_qos() is not setting all of rmw_qos_profile_t

- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
Currently, publishers have the get_actual_qos() feature/function. It would make sense for subscriptions to have them, too.
> Implement get_actual_qos() for subscriptions

- rmw_fastrtps_shared_cpp/src/qos.cpp
**Required Info:**
- Operating System:
- Fedora 30
- Installation type:
- source
- Version or commit hash:
- 0.7.3
- DDS implementation:
- Fast-RTPS
- Client library (if applicable):
- N/A
Compile from source using system's default compiler, `g++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)`
No warnings.
```
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp: In instantiation of ‘bool fill_entity_qos_from_profile(const rmw_qos_profile_t&, DDSEntityQos&, eprosima::fastrtps::HistoryQosPolicy&) [with DDSEntityQos = eprosima::fastrtps::ReaderQos; rmw_qos_profile_t = rmw_qos_profile_t]’:
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp:150:86:   required from here
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp:98:28: warning: comparison of integer expressions of different …
```
> Fix compile warning with -Wsign-compare

- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
Working against the release/1.8.1 branch on Fast-RTPS.
It doesn't provide the Participant::assert_liveliness API, but it has added this API for Publishers.
> Enable assert liveliness on publisher.

- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
Enable participant assert_liveliness and MANUAL_BY_NODE liveliness policy, since they are supported in v1.8.1
Signed-off-by: Emerson Knapp <eknapp@amazon.com>
> Enable manual_by_node and node liveliness assertion

- rmw_fastrtps_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
Connects to https://github.com/ros2/rmw/pull/179
> Add function for getting clients by node

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
Fixes https://github.com/ros2/rmw_fastrtps/issues/299.
> Add missing lock guards for discovered_names and discovered_namespaces

- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/src/type_support_common.hpp
- rmw_fastrtps_shared_cpp/src/demangle.cpp
Backport #291
Depends on ros2/rcpputils#17
> Use rcpputils::find_and_replace instead of std::regex_replace

- rmw_fastrtps_shared_cpp/src/qos.cpp
This is a backport of #288 for Dashing.
---
**Required Info:**
- Operating System:
- Fedora 30
- Installation type:
- source
- Version or commit hash:
- 0.7.3
- DDS implementation:
- Fast-RTPS
- Client library (if applicable):
- N/A
Compile from source using system's default compiler, `g++ (GCC) 9.1.1 20190503 (Red Hat 9.1.1-1)`
No warnings.
```
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp: In instantiation of ‘bool fill_entity_qos_from_profile(const rmw_qos_profile_t&, DDSEntityQos&, eprosima::fastrtps::HistoryQosPolicy&) [with DDSEntityQos = eprosima::fastrtps::ReaderQos; rmw_qos_profile_t = rmw_qos_profile_t]’:
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp:150:86:   required from here
src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/qos.cpp:98:28: warning: …
```
> [Backport] Fix compile warning with -Wsign-compare

- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
I guess this will solve this failure in the nightlies:
https://ci.ros2.org/view/nightly/job/nightly_win_rel/1310/testReport/junit/rmw_fastrtps_shared_cpp/cppcheck/error__syntaxError__src_rmw_wait_set_cpp_50_/
> Correct linter failure

- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
Addresses https://github.com/ros2/ros2cli/pull/322#issuecomment-525364023
> Return specific error code when node is not found

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
Made sure this change is reflected in places where the function is
called; namely in rmw_publisher.cpp and rmw_subscription.cpp
Note: colcon build and test for packages-up-to rmw_fastrtps_shared_cpp
built successfully and passed the tests without any failures or errors.
Signed-off-by: Jaison Titus <jaisontj92@gmail.com>
> Renamed dds_qos_to_rmw_qos to dds_attributes_to_rmw_qos

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
PR to implement [network traffic restriction for localhost](https://github.com/ros2/ros2/issues/798). There are no test yet since this is a mock open for implementation discussion. Connected to [rmw](https://github.com/ros2/rmw/pull/190)
- Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=8441)](https://ci.ros2.org/job/ci_linux/8441/)
- Arch [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=4343)](https://ci.ros2.org/job/ci_linux-aarch64/4343/)
- Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=8352)](https://ci.ros2.org/job/ci_windows/8352/)
- OSX [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=6866)](https://ci.ros2.org/job/ci_osx/6866/)
> Restrict traffic to localhost only if env var is provided

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
connects to https://github.com/ros2/rclcpp/pull/896
Signed-off-by: Karsten Knese <karsten@openrobotics.org>
> rename return functions for loaned messages

- rmw_fastrtps_shared_cpp/src/rmw_get_topic_endpoint_info.cpp
Fixes https://github.com/ros2/rmw_fastrtps/issues/344
Fixes https://github.com/ros-security/aws-oncall/issues/52
This PR fixes the warnings in the clang thread safety analysis build by adding a lock guard around use of the `discovered_names` variable in `rmw_get_topic_endpoint_info.cpp`
Signed-off-by: Emerson Knapp <emerson.b.knapp@gmail.com>
> Fix unprotected use of mutex-guarded variable

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/topic_cache.hpp
- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
- rmw_fastrtps_shared_cpp/src/demangle.cpp
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/test/test_topic_cache.cpp
Style update to match the ROS 2 development guide and pass with the updated linter configuration from ament/ament_lint#210.
> code style only: wrap after open parenthesis if not in one line

- rmw_fastrtps_shared_cpp/src/rmw_get_topic_endpoint_info.cpp
Depends on https://github.com/ros2/rmw/pull/196.
Now, `rmw_topic_endpoint_info_array` initializes `size` to the correct value.
So there's not need of doing that again.
> Update rmw_topic_endpoint_info_array usage

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/guid_utils.hpp
- rmw_fastrtps_shared_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Fixes https://ci.ros2.org/job/ci_linux/9175/warnings23Result/package.936823267/.
```
‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘struct eprosima::fastrtps::rtps::GUID_t’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
--
```
> Fix build warning in Ubuntu Focal

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_common.hpp
- rmw_fastrtps_dynamic_cpp/src/type_support_proxy.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_registry.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_registry.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/locked_object.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/topic_cache.hpp
This should fix #265 with `rmw_fastrtps_dynamic_cpp`.
> Fixing type support C/CPP mix on rmw_fastrtps_dynamic_cpp

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/rmw_event.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_event.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_event.cpp
- rmw_fastrtps_shared_cpp/src/types/event_types.hpp
Related to https://github.com/ros2/ros2/issues/822
This adds the `rmw_publisher_event_init()` and `rmw_subscription_event_init()` functions to `rmw_fastrtps`, moved from `rmw`, so that these functions will be able to check for whether or not the given type of `rmw_event_type_t` is supported by the chosen middleware.
> Add rmw_*_event_init() functions

- rmw_fastrtps_shared_cpp/src/rmw_event.cpp
Follow up of https://github.com/ros2/rmw_fastrtps/pull/354.
In this way, it prints `rmw_fastrtps_cpp` or `rmw_fastrtps_dynamic_cpp` accordingly.
> Correct error message when event is not supported

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/macros.hpp
> rename rosidl_generator_c namespace to rosidl_runtime_c

- rmw_fastrtps_shared_cpp/src/participant.cpp
This PR adds a small change to support the only API break between Fast RTPS 1.10.x and master branch, which will soon become version 2.0.0
I have just run ros2 tests locally with [this branch](https://github.com/eProsima/Fast-RTPS/tree/feature/shm-fixes/master) that also enables shared memory transport by default.
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Support for API break on Fast RTPS 2.0

- rmw_fastrtps_shared_cpp/CMakeLists.txt
> export targets in a addition to include directories / libraries

- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
FastRTPS doesn't have built-in support for taking multiple samples, so
this implementation utilizes a loop over the `take` function multiple
times.
Implementation of ros2/rmw#212.
Signed-off-by: Michael Carroll <michael@openrobotics.org>
> Add support for taking a sequence of messages

- rmw_fastrtps_cpp/CMakeLists.txt
Related to ros2/ros2#904.
Usage: https://github.com/ros2/rmw_fastrtps/blob/19745ab1bd5177d32a1b0e034479215180afa384/rmw_fastrtps_cpp/CMakeLists.txt#L99
> add missing export of rmw_dds_common

- rmw_fastrtps_cpp/Doxyfile
- rmw_fastrtps_dynamic_cpp/Doxyfile
- rmw_fastrtps_shared_cpp/Doxyfile
Added Doxyfile to `rmw_fastrtps_cpp`, `rmw_fastrtps_dynamic_cpp` and `rmw_fastrtps_shared_cpp` in the process of reaching Quality Level 1.
> Added doxyfiles

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_cpp/README.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/README.md
This adds QUALITY_DECLARATION files for rmw_fastrtps_cpp and rmw_fastrtps_shared_cpp and package-level READMEs.
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Add package READMEs and QUALITY_DECLARATION files

- rmw_fastrtps_shared_cpp/src/rmw_security_logging.cpp
Follow-up from https://github.com/ros2/rmw_fastrtps/pull/362
This warning is showing up on build.ros2.org: http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps_ubuntu_focal_amd64/106/gcc/new/
> Fix unused variabled warning

- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
The current implementation is actually broken, which wasn't detected because the test is too dumb. This fixes the implementation, I'll fix the test in another PR.
@ivanpauno first part of the fix.
> Fill service_info timestamps from sample_info

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
Precisely what the title says. As discussed offline, we defer unit testing and rely on integration and system tests up the stack (at least for the time being).
> Update quality declarations on feature testing.

- rmw_fastrtps_shared_cpp/package.xml
- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
- rmw_fastrtps_shared_cpp/test/test_rmw_init_options.cpp
Precisely what the title says.
> Add test coverage for rmw_init_options API.

- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
- rmw_fastrtps_shared_cpp/test/test_guid_utils.cpp
Precisely what the title says. These tests simply verify that conversion in both directions is possible.
> Add test coverage for GUID utilities.

- rmw_fastrtps_shared_cpp/test/test_guid_utils.cpp
- rmw_fastrtps_shared_cpp/test/test_names.cpp
Fixes a regression introduced by https://github.com/ros2/rmw_fastrtps/pull/388.
CI up to `rmw_fastrtps_shared_cpp`, building for Release:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=10932)](http://ci.ros2.org/job/ci_linux/10932/)
> Do not compile assert death tests in Release builds.

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
This PR adds a link to REP-2006 (the Security Vulnerability Declaration) to the Quality Declaration for this repository.
Connects to ros2/ros2#924.
> QD Security Vulnerability Declaration: REP 2006

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/guid_utils.hpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
This addresses ros2/ros2#922
The idea is to send the GUID of the response subscription on each request (using related_sample_identity), so the service could check if that reader is already matched to the response publisher when sending the response.
I've made the changes so they are backwards compatible. The service will only use and check the related guid when received. The client will check the received related guid against both the response reader and the request writer, in case an old service answers with the latter.
> Make service wait for response reader

- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_context_impl.hpp
This pull request ensures `rmw_context_fini()` fails on a not shutdown context, as its API contract establishes (see https://github.com/ros2/rmw/pull/242).
> Finalize context if and only if it's shutdown.

- rmw_fastrtps_shared_cpp/src/rmw_init.cpp
Complying with https://github.com/ros2/rmw/pull/244.
> Ensure compliant init options API implementations.

- rmw_fastrtps_shared_cpp/test/test_rmw_init_options.cpp
Closes https://github.com/ros2/rmw_fastrtps/issues/400. Compilers are not bound to overlap storage.
Windows debug CI up to `rmw_fastrtps_shared_cpp`:
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=11195)](http://ci.ros2.org/job/ci_windows/11195/)
> Do not use string literals as implementation identifiers in tests.

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_cpp/README.md
Precisely what the title says. I may or may not update the dependencies' listing based on https://github.com/ros2/rosidl_typesupport/pull/77#discussion_r445662985 outcome.
> Update Quality Declaration to QL3.

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
To comply with https://github.com/ros2/rmw/pull/243.
> Ensure compliant init/shutdown API implementation.

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/README.md
Follow up after #403. Updates `rmw_fastrtps_shared_cpp` QD and corrects a mistake in `rmw_fastrtps_cpp`'s.
> Update Quality Declarations to QL3.

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
See https://github.com/ros2/rcl/pull/708.
> Remove domain_id and localhost_only from node API

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
Addresses https://github.com/ros2/rmw_fastrtps/pull/390#discussion_r455136217. Looks like thread safety analysis isn't smart enough.
> Add missing thread-safety annotation in ServicePubListener

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/guid_utils.hpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
Backport #390 to Foxy.
Note, this breaks ABI compatibility, but only below the RMW layer. IMO, the breakage is acceptable considering the improvement to service discovery.
I'm still checking if this change is backports compatible over the wire.
> Make service wait for response reader (#390)

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
> [foxy backport] Add missing thread-safety annotation in ServicePubListener (#409)

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/src/publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
Precisely what the title says. Connected to https://github.com/ros2/rmw/pull/252.
> Ensure compliant publisher API.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/MessageTypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/ServiceTypeSupport.hpp
I found the following problem while trying to run the ABI checker:
```
In file included from /tmp/xtQxIqHDSj/dump1.h:43:
/tmp/tmp3ci40kvk/files/opt/ros/foxy/include/rmw_fastrtps_shared_cpp/MessageTypeSupport.hpp:30:46: error: expected template-name before ‘<’ token
30 | class MessageTypeSupport : public TypeSupport<MembersType>
|                                              ^
/tmp/tmp3ci40kvk/files/opt/ros/foxy/include/rmw_fastrtps_shared_cpp/MessageTypeSupport.hpp:30:46: error: expected ‘{’ before ‘<’ token
In file included from /tmp/xtQxIqHDSj/dump1.h:49:
/tmp/tmp3ci40kvk/files/opt/ros/foxy/include/rmw_fastrtps_shared_cpp/ServiceTypeSupport.hpp:30:46: error: expected template-name before ‘<’ token
30 | class ServiceTypeSupport : public TypeSupport<MembersType>
| …
```
> Use package in path to TypeSupport header for ServiceTypeSupport/MessageTypeSupport

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
This PR is related to https://github.com/ros2/rclcpp/issues/1242
Signed-off-by: Chen.Lihui <lihui.chen@sony.com>
> Fix trying to get topic data that was already removed.

- rmw_fastrtps_shared_cpp/src/subscription.cpp
Fixes regression introduced by 94b379e9245d31c2c1ed8344751674c0dfd6e26c / #419.
CI up to `rmw_fastrtps_shared_cpp` in `Release` mode:
* Linux [![Build Status](https://ci.ros2.org/buildStatus/icon?job=ci_linux&build=11802)](https://ci.ros2.org/job/ci_linux/11802/)
> Avoid unused identifier variable warnings.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/MessageTypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/ServiceTypeSupport.hpp
> Use package path to TypeSupport.hpp headers in ServiceTypeSupport and MessageTypeSupport (foxy backport)

- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
Related to https://github.com/ros2/rcl/issues/721
<details><summary>memory leak log </summary>
<p>
```shell
==23229== 784 (168 direct, 616 indirect) bytes in 7 blocks are definitely lost in loss record 15 of 16
==23229==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23229==    by 0x5CFD615: __default_allocate (allocator.c:35)
==23229==    by 0x797FF24: rmw_allocate (allocators.c:29)
==23229==    by 0x79800C0: rmw_wait_set_allocate (allocators.c:133)
==23229==    by 0x84254B9: rmw_fastrtps_shared_cpp::__rmw_create_wait_set(char const*, rmw_context_t*, unsigned long) (rmw_wait_set.cpp:38)
==23229==    by 0x83EEAEA: node_listener(rmw_context_t*) (listener_thread.cpp:132)
==23229==    by 0x83EF3B6: void std::__invoke_impl<void, void (*)(rmw_context_t*), …
```
> Fix memory leak that wait_set might be not destroyed in some case.

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
Follow-up after 8fc9ca3d98a64118590a205b2162559e17309a27 (#414).
> Ensure compliant publisher QoS queries.

- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
Cherry-pick #423 to foxy.
Signed-off-by: Chen.Lihui <lihui.chen@sony.com>
> [foxy] Fix memory leak that wait_set might be not destoryed in some case. (#423)

- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
Handle errors consistently. Do not assume allocation will always succeed.
> Improve __rmw_create_wait_set() implementation.

- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
This fixes #428 by using a similar approach to ros2/rmw_cyclonedds#228
It also addresses #219
> Avoid memory leaks and undefined behavior in rmw_fastrtps_dynamic_cpp typesupport code

- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
> Updated error returns on rmw_publish to comply with documentation

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
> Call Domain::removePublishe while failure occurs in create_publisher

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
> Updated error returns on rmw_take

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
> Updated error returns on rmw_take_serialized and with_message_info 

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
Precisely what the title says. `rmw_fastrtps_shared_cpp::__rmw_destroy_publisher` attempts to update (and lock) the graph again, while `rmw_fastrtps_shared_cpp::destroy_publisher` does not.
> Avoid deadlock if graph update fails.

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/test/test_get_native_entities.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/test/test_get_native_entities.cpp
Precisely what the title says. These getters are `rmw_fastrtps*_cpp`  specific public API.
CI up to `rmw_fastrtps_cpp` and `rmw_fastrtps_dynamic_cpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12381)](http://ci.ros2.org/job/ci_linux/12381/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7350)](http://ci.ros2.org/job/ci_linux-aarch64/7350/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10093)](http://ci.ros2.org/job/ci_osx/10093/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12293)](http://ci.ros2.org/job/ci_windows/12293/)
> Add tests for native entity getters

- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/src/rmw_get_topic_endpoint_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_info_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node_names.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_names_and_types.cpp
- rmw_fastrtps_shared_cpp/src/rmw_topic_names_and_types.cpp
Connected to https://github.com/ros2/rmw/pull/272. This pull request affects:
- `rmw_get_node_names()`
- `rmw_get_node_names_with_enclaves()`
- `rmw_get_topic_names_and_types()`
- `rmw_get_service_names_and_types()`
- `rmw_get_publishers_info_by_topic()`
- `rmw_get_subscriptions_info_by_topic()`
- `rmw_get_subscriber_names_and_types_by_node()`
- `rmw_get_publisher_names_and_types_by_node()`
- `rmw_get_service_names_and_types_by_node()`
- `rmw_get_client_names_and_types_by_node()`
- `rmw_count_publishers()`
- `rmw_count_subscribers()`
> Update graph API return codes.

- rmw_fastrtps_shared_cpp/src/rmw_compare_gids_equal.cpp
- rmw_fastrtps_shared_cpp/src/rmw_get_gid_for_publisher.cpp
To be compliant with the API spec. Connected to https://github.com/ros2/rmw/pull/274.
> Update gid API return codes.

- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
Precisely what the title says. To bump coverage leveraging fault injection tests in upper layers.
Full CI:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12389)](http://ci.ros2.org/job/ci_linux/12389/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7357)](http://ci.ros2.org/job/ci_linux-aarch64/7357/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10100)](http://ci.ros2.org/job/ci_osx/10100/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12301)](http://ci.ros2.org/job/ci_windows/12301/)
> Inject faults on __rmw_publish() and run_listener_thread() call.

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
Connected to https://github.com/ros2/rmw/pull/276. This pull request simply updates return codes for `rmw_fastrtps_dynamic_cpp`, but refactors `rmw_fastrtps_cpp` (i.e. `new` expressions cannot be allowed to throw).
> Make service/client construction/destruction implementation compliant

- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
- rmw_fastrtps_shared_cpp/test/test_rmw_qos_to_dds_attributes.cpp
Precisely what the title says.  
CI up to `rmw_fastrtps_shared_cpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12447)](http://ci.ros2.org/job/ci_linux/12447/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7414)](http://ci.ros2.org/job/ci_linux-aarch64/7414/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10157)](http://ci.ros2.org/job/ci_osx/10157/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12362)](http://ci.ros2.org/job/ci_windows/12362/)
> Add tests for RMW QoS to DDS attribute conversion.

- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
See https://github.com/ros2/rosidl/pull/531.
> Fix array `get_function` semantics

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/test/test_logging.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/test/test_logging.cpp
- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
- rmw_fastrtps_shared_cpp/test/test_logging.cpp
Added rmw_logging tests to:
- rmw_fastrtps_cpp
- rmw_fastrtps_dynamic_cpp
- rmw_fastrtps_shared_cpp
> Added rmw_logging tests

- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
> Update service/client request/response API error returns

- rmw_fastrtps_cpp/src/rmw_serialize.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_serialize.cpp
Return the right error code. Related with https://github.com/ros2/rmw/pull/281
> Return RMW_RET_UNSUPPORTED in rmw_get_serialized_message_size

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
Precisely what the title says.
> Update rmw_fastrtps_cpp and rmw_fastrtps_shared_cpp QDs to QL2.

- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/test/test_rmw_qos_to_dds_attributes.cpp
A bug I came across while looking for more lines to cover.
CI up to `rmw_fastrtps_shared_cpp` and `rcl`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12571)](http://ci.ros2.org/job/ci_linux/12571/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7539)](http://ci.ros2.org/job/ci_linux-aarch64/7539/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10282)](http://ci.ros2.org/job/ci_osx/10282/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12496)](http://ci.ros2.org/job/ci_windows/12496/)
> Handle too large QoS queue depths. 

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
Precisely what the title says. Destruction should never return early i.e. partially destruct an object. This patch ensures this is the case _and_ that no error gets lost. 
CI up to `rcl` and `test_rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=12585)](http://ci.ros2.org/job/ci_linux/12585/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=7552)](http://ci.ros2.org/job/ci_linux-aarch64/7552/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10297)](http://ci.ros2.org/job/ci_osx/10297/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=12510)](http://ci.ros2.org/job/ci_windows/12510/)
Hopefully this will fix the flakes we've seen …
> Ensure rmw_destroy_node() completes despite run-time errors.

- README.md
- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_cpp/README.md
- rmw_fastrtps_dynamic_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_dynamic_cpp/README.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/README.md
* Update name to Fast DDS instead of Fast-RTPS
* Provide links to the Quality Declarations for the external dependencies
* Add Quality Declaration for `rmw_fastrtps_dynamic_cpp`
* Add README for `rmw_fastrtps_dynamic_cpp`
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
> Update Quality Declarations and READMEs

- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_shared_cpp/package.xml
> Update the package.xml files with the latest Open Robotics maintainers

- README.md
Explanation about how to use environment variable `RMW_FASTRTPS_USE_QOS_FROM_XML` can be clearer preventing misunderstandings and issues that some users have reported (#465)
> Update README to clarify the use of environment variable RMW_FASTRTPS_USE_QOS_FROM_XML

- README.md
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
Several issues are related to the default publication mode set in `rmw_fastrtps` which is `ASYNCHRONOUS` publish mode.
This configuration can be changed only if the user defines a XML file and also sets the environment variable `RMW_FASTRTPS_USE_QOS_FROM_XML` to 1. This could be cumbersome to the user and also, as the issues show, prone to errors.
This pull request uses a new environment variable `RMW_FASTRTPS_PUBLICATION_MODE` so the user can change easily the publishing mode without needing to define a XML file.
This new environment variable can be used also in other RMW implementations and the values that have been considered are the following (this is open to discussion and more values can be given to this new environment variable):
* `ASYNCHRONOUS`: asynchronous publishing mode …
> New environment variable to change easily the publication mode

- rmw_fastrtps_shared_cpp/src/qos.cpp
Full description and discussion here:
https://github.com/ros2/rmw_dds_common/pull/37
> Use new time_utils function to limit rmw_time_t values to 32-bits

- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
Some users are trying to build dashing from sources using Fast DDS 2.0.x.
This PR contains changes equivalent to the ones in #370 to support that.
Signed-off-by: Miguel Company <miguelcompany@eProsima.com>
> [dashing] Support for API break on Fast DDS 2.0

- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
Attempt to backport #467 to Foxy in an ABI compatible way.
I *think* this is an ABI compatible port; I'll let the ABI checking tell me otherwise.
> [foxy] Discriminate when the Client has gone from when the Client has not completely matched

- rmw_fastrtps_shared_cpp/src/participant.cpp
This fixes the build problems on windows for ros2/ros2#1058
I also changed a parameter of a static function from value to const reference, in order to avoid an unnecessary copy
> Remove unnecessary includes

- rmw_fastrtps_shared_cpp/src/init_rmw_context_impl.cpp
This was found during scan-build, but the return value `ret` is not actually returned here. I suspect it was meant to be returned at the end of the if statement? 
Once this is resolved, scan-build passes cleanly for `rmw_fastrtps_cpp` and `rmw_fastrtps_shared_cpp`
Signed-off-by: Stephen Brawner <brawner@gmail.com>
> Make use of error return value in decrement_context_impl_ref_count

- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
This reverts commit c78c31a825932d9cc6682120d06e6fcea733a3bb from #479 @jacobperron FYI
It appears to be the cause of [Foxy CI with `rmw_fastrtps_dynamic_cpp` hanging](http://build.ros2.org/view/Fci/job/Fci__nightly-fastrtps-dynamic_ubuntu_focal_amd64/205/). It causes the rclcpp composable node container to crash, and that causes a test in `test_launch_ros` to hang forever.
A more minimal example is:
```
$ export RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp
$ ./install/rclcpp_components/lib/rclcpp_components/component_container
```
```
$ export RMW_IMPLEMENTATION=rmw_fastrtps_dynamic_cpp
$ ros2 component list
```
When `ros2 component list` is called, the container segfaults.
<details><summary>Crash happens entirely in FastRTPS</summary>
```
#0  0x00007ffff6e9e4c4 in …
```
> Revert "Discriminate when the Client has gone from when the Client has not completely matched (#479)"

- rmw_fastrtps_shared_cpp/src/participant.cpp
After eProsima/Fast-DDS#1520, this should fix the second part of ros2/ros2#1052
Signed-off-by: Miguel Company <MiguelCompany@eprosima.com>
> Use interface whitelist for localhost only

- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
#467 introduced an API break that it is not required for the workaround. This pull request reverts that break.
Signed-off-by: JLBuenoLopez-eProsima <joseluisbueno@eprosima.com>
> Revert ServicePubListener API break

- rmw_fastrtps_cpp/src/rmw_init.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_init.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
Added checks for the creation of nodes in context which has been shutdown, and for shutdown of a context with active nodes. 
Thess throw a `RMW_RET_ERROR` instead of causing segfaults as seen in ros2/rmw_fastrtps#478
Signed-off-by: Ignacio Montesino <ignaciomontesino@eprosima.com>
> Check for correct context shutdown

- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
Revert #489 (9094971) and add a patch to fix the reported bug (34a23d5).
I think the issue was that the shared function for sending the service response [assumes we are using the patched version of the service listener](https://github.com/ros2/rmw_fastrtps/blob/34a23d51d4611cb5398c11e827bcc67fc02ccc13/rmw_fastrtps_shared_cpp/src/rmw_response.cpp#L121), and I had not updated the `rmw_fastrtps_dynamic_cpp` implementation to use this type. This PR fixes that issue.
> [foxy] Redo "Discriminate when the Client has gone from when the Client has not completely matched"

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
There were actually 2 problems here:
1.  We were missing the lock in check_for_subscription()
completely (this is the original issue that caused me to
examine this code).
2.  We had an accessor for clients_endpoints_ so that external
users could get a reference.  But with that being the case,
any access to the returned reference would be without a lock.
Since we were only accessing client_endpoints_ in two places,
make some methods in ServicePubListener to do the requested
operations while holding the lock, getting rid of the problem.
I was initially investigating an issue pointed out by https://ci.ros2.org/view/nightly/job/nightly_linux_clang_libcxx/627/gcc/new/ , but upon review of the code I found both problems above.  I …
> Make sure to lock the mutex protecting client_endpoints_.

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
Follow-up after https://github.com/ros2/rosidl_typesupport/pull/99. Missing error handling code caused test failures in downstream packages (e.g. https://ci.ros2.org/view/nightly/job/nightly_linux-aarch64_release/1415/). This patch addresses them.
Full CI (just in case):
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13273)](http://ci.ros2.org/job/ci_linux/13273/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8205)](http://ci.ros2.org/job/ci_linux-aarch64/8205/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=10993)](http://ci.ros2.org/job/ci_osx/10993/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13304)](http://ci.ros2.org/job/ci_windows/ …
> Handle typesupport errors on fetch.

- rmw_fastrtps_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_dynamic_cpp/src/init_rmw_context_impl.cpp
Otherwise, during stack unwinding, the graph cache may end up with a callback that captures and uses an already destroyed guard condition.
This patch (hopefully) fixes #491. 
Ci up `test_rmw_implementation`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=13277)](http://ci.ros2.org/job/ci_linux/13277/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=8209)](http://ci.ros2.org/job/ci_linux-aarch64/8209/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=11008)](http://ci.ros2.org/job/ci_osx/11008/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=13311)](http://ci.ros2.org/job/ci_windows/13311/)
> Set rmw_dds_common::GraphCache callback after init succeeds.

- README.md
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
When loading configuration from a Fast DDS XML file, the current code uses the same publisher profile for all publishers and the same subscriber profile for all subscribers.
This PR aims to change this behavior, allowing the user to specify different settings on each publisher or subscriber, according to the following rules:
If a `<publisher>` profile with `profile_name=topic_name` exists in FASTRTPS_DEFAULT_PROFILES_FILE, then load it.
Otherwise, use the `<publisher>` profile with `is_default_profile="true"`
If a `<subscriber>` profile with `profile_name=topic_name` exists in FASTRTPS_DEFAULT_PROFILES_FILE, then load it.
Otherwise, use the `<subscriber>` profile with `is_default_profile="true"`
For the creation of the request subscriber, if a `<subscriber>` profile with …
> Load profiles based on topic names

- rmw_fastrtps_shared_cpp/src/subscription.cpp
Backport #422 to Foxy.
This should resolve compiler warnings in release builds, e.g. https://ci.ros2.org/job/ci_packaging_osx/79/clang/
> [foxy] Avoid unused identifier variable warnings (#422)

- README.md
This PR extends XML examples to include different profile types selected by name.
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
> Extend XML examples

- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
This PR adds to `rmw_fastrtps_dynamic_cpp` the functionality included in #335 
Signed-off-by: EduPonz <eduardoponz@eprosima.com>
> Load profiles based on topic names in rmw_fastrtps_dynamic_cpp

- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
This, along with eProsima/Fast-CDR#98 should fix the crashes found on ros2/ros2cli#586.
> Capture cdr exceptions

- rmw_fastrtps_shared_cpp/src/participant.cpp
foxy backport of https://github.com/ros2/rmw_fastrtps/pull/476
> [foxy] Use interface whitelist for localhost only (#476)

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/qos.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/test/test_dds_attributes_to_rmw_qos.cpp
- rmw_fastrtps_shared_cpp/test/test_rmw_qos_to_dds_attributes.cpp
Depends on https://github.com/ros2/rmw/pull/301
Meets the new API expectations introduced in https://github.com/ros2/rmw/pull/301 - to accept and return `RMW_DURATION_INFINITE` for cross-implementation consistency.
> Take and return new RMW_DURATION_INFINITE correctly

- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_dynamic_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
Updating obsolete links in the QUALITY_DECLARATION.md files, re: ros2/docs.ros2.org#52
> Updating Quality Declaration

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_get_endpoint_network_flow.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_get_endpoint_network_flow.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_get_endpoint_network_flow.cpp
This PR implements unique network flows for publishers and subscribers in communicating nodes.
Depends on ros2/ros2#1112
Associated pull-requests:
* [design](https://github.com/ros2/design/pull/304)
* [examples](https://github.com/ros2/examples/pull/296)
* [rclcpp](https://github.com/ros2/rclcpp/pull/1496)
* [rcl](https://github.com/ros2/rcl/pull/880)
* [rmw](https://github.com/ros2/rmw/pull/294)
* [rmw_implementation](https://github.com/ros2/rmw_implementation/pull/170)
* [Fast DDS](https://github.com/eProsima/Fast-DDS/pull/1682)
Initial contributions stem from Ericsson and eProsima.
> Unique network flows

- rmw_fastrtps_shared_cpp/src/participant.cpp
- rmw_fastrtps_shared_cpp/src/rmw_security_logging.cpp
https://github.com/ros2/rcutils/pull/340 deprecates `rcutils/get_env.h`. This PR doesn't need to wait until the `rcutils` PR is merged, though.
> Update includes after rcutils/get_env.h deprecation

- rmw_fastrtps_shared_cpp/CMakeLists.txt
Precisely what the title says.
CI up to `rmw_fastrtps_cpp`:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=14586)](http://ci.ros2.org/job/ci_linux/14586/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=9341)](http://ci.ros2.org/job/ci_linux-aarch64/9341/)
* macOS [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_osx&build=12250)](http://ci.ros2.org/job/ci_osx/12250/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=14715)](http://ci.ros2.org/job/ci_windows/14715/)
> Export rmw_dds_common as an rmw_fastrtps_shared_cpp dependency

- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/time_utils.cpp
- rmw_fastrtps_shared_cpp/src/time_utils.hpp
> Add rmw_publisher_wait_for_all_acked support

- rmw_fastrtps_shared_cpp/src/participant.cpp
Backport #487 into foxy.
Should fix the build issues on windows for ros2/ros2#1114 and ros2/ros2#1113
> [Foxy] Remove unnecessary includes

- README.md
- rmw_fastrtps_cpp/QUALITY_DECLARATION.md
- rmw_fastrtps_shared_cpp/QUALITY_DECLARATION.md
And make a few other minor updates while we are in here.
> Change links from index.ros.org -> docs.ros.org

- rmw_fastrtps_shared_cpp/src/participant.cpp
This gets rid of a bunch of custom code for finding the
paths to the security files.
This requires https://github.com/ros2/rmw_dds_common/pull/51 to go in first.
> Use the new rmw_dds_common::get_security_files

- rmw_fastrtps_shared_cpp/src/participant.cpp
If the rmw_dds_common layer tells us that a CRL file is
available, set the appropriate property so Fast-DDS will
honor it.
Note that this can be merged at any time, but will have no effect until https://github.com/ros2/rmw_dds_common/pull/52 is merged.
> Pass the CRL down to Fast-DDS if available.

- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
Account for possible RTPS submessage alignment.
The DDSI-RTPS spec requires each submessage to be aligned on a 4-byte boundary. This means that, when using `PREALLOCATED` memory policy, we could receive a serialized payload bigger than `m_typeSize`, which would thus be discarded. When using the rmw's default `PREALLOCATED_WITH_REALLOC` memory policy, an unnecessary reallocation could happen.
> Fix type size alignment

- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
This PR fixes a bug introduced in `rmw_fastrtps_dynamic_cpp` by #523, where the serialized size of a bounded sequence is being always calculated as the maximum possible serialized size.
It also gets ready for the fix on ros2/rosidl_typesupport_fastrtps#71
> Correctly recalculate serialized size on bounded sequences

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publish.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_take.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publish.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_take.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_proxy.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/subscription.hpp
- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
This is a backport of #523 into galactic without the need of ros2/rosidl_typesupport_fastrtps#67
> [Galactic] Loan messages implementation

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
The original motivation to do this is to please the clang
thread safety analysis, which can't quite figure out the
locking regime with an external mutex.  Instead, move major
functionality into the LoanManager class, and then mark
the item list as private.
One thing to note is that the logic of
__rmw_take_loaned_message_internal is slightly changed here.
Before it would emplace an Item onto the LoanManager's list,
then look through the data_reader to see if it could take an
item.  If it could, it would just fill that Item in and return.
If it couldn't, it would pop that item out of the list.  This
commit changes it so that we instantiate a temporary Item.
If we can take an item, we then push that Item into the LoanManager
list.  We never pop it.  This should be equivalent (and
slightly …
> Update the LoanManager to do internal locking.

- README.md
This PR addresses ros2/rmw_fastrtps#554. It explains how to name an `publisher` or `subscriber` XML profile so it is selected for publishers or subscribers on given topics.
Signed-off-by: Eduardo Ponz Segrelles <eduardoponz@eprosima.com>
> Clarify rule for selecting a XML profile using topic name

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_context_impl.hpp
Connected to https://github.com/ros2/rmw/pull/313.
> Update rmw_context_impl_t definition

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
Links to https://github.com/ament/uncrustify_vendor/pull/27 ; see that PR for more information and CI.
> Fixes for uncrustify 0.72

- README.md
- rmw_fastrtps_shared_cpp/src/participant.cpp
@JaimeMartin and @MiguelCompany, is this the right way to make synchronous the default?
> Change default to synchronous

- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
> [foxy] Avoid memory leaks and undefined behavior in rmw_fastrtps_dynamic_cpp typesupport code (#429)

- rmw_fastrtps_cpp/src/rmw_serialize.cpp
The functions rmw_deserialize and rmw_serialize in the file rmw_seralize.cpp created an instance of the class MessageTypeSupport_cpp on the heap but this instances can also be allocated on the stack.
This change removes 2 new and 2 delete calls which makes serialization and deserialization faster and enables this code to be hard realtime capable.
PS: I hope I got the sign-off correct now,...
Signed-off-by: Martin Mayer <martin.mayer@gmx.de>
> Removed some heap interactions in rmw_serialize.cpp

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/rmw_features.cpp
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_features.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_features.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Implements https://github.com/ros2/rmw/pull/318.
`reception_sequence_number` doesn't seem to be available in fastrtps.
> Add sequence numbers to message info structure

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/subscription.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/utils.hpp
- rmw_fastrtps_shared_cpp/package.xml
- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/src/utils.cpp
Related to https://github.com/ros2/design/pull/282 to add content-filtered-topic interfaces.
> Add content filter topic feature

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/package.xml
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
This adds tracing instrumentation using `tracetools` for publisher/subscription initialization at the `rmw` level. By recording the pub/sub GIDs, we can match ROS 2 pubs/subs with the corresponding DDS writers/readers.
This also adds a tracepoint for `rmw_publish` and `rmw_take` so that we can track published/taken messages at the rmw level.
For simplicity, this only adds instrumentation for `rmw_fastrtps_cpp` and not `rmw_fastrtps_dynamic_cpp`, since the former is the default RMW implementation while the latter is a [tier 2 implementation](https://www.ros.org/reps/rep-2000.html#id41).
Equivalent to this PR for `rmw_cyclonedds_cpp`: https://github.com/ros2/rmw_cyclonedds/pull/329. Since the default RMW implementation was changed from `rmw_cyclonedds_cpp` to `rmw_fastrtps_cpp`, it would be …
> Add pub/sub init, publish and take instrumentation using tracetools

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
Connects to https://github.com/ros2/rmw/pull/320
If users set certain QoS policies to BEST_AVAILABLE, then we query the graph for endpoint info.
The policy is updated such that it is compatible with all endpoints while maintaining the
highest possible level of service.
> Handle 'best_available' QoS policies

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_event.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_event.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
Fixes https://github.com/ros2/rmw_fastrtps/issues/599
Two commits:
* Copy the implementation done in #468 for dynamic version
* Add some check to parameters passed to fastrtps_cpp to keep both implementations in sync
Testing:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16644)](http://ci.ros2.org/job/ci_linux/16644/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11226)](http://ci.ros2.org/job/ci_linux-aarch64/11226/)
* Windows [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_windows&build=17042)](http://ci.ros2.org/job/ci_windows/17042/)
I think that cpplint is not related to this PR. I can open a new PR to fix it.
> Add EventsExecutor API for dynamic_fastrtps

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_event.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_event.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
After merging #600, failing tests have appeared in rclcpp that points to problems with assertions introduced on parameter there.
I did that following the [API](https://docs.ros.org/en/ros2_packages/rolling/api/rmw/generated/function_rmw_8h_1a2195fea162b6f4b30f2d7bdd00a56401.html ) that explicit mention when a parameter can be null (i.e. `user_data`). Seems to me like the null check and error handling is being done at a different place of the stack.
Testing:
* Linux [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=16652)](http://ci.ros2.org/job/ci_linux/16652/)
* Linux-aarch64 [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux-aarch64&build=11237)](http://ci.ros2.org/job/ci_linux-aarch64/11237/)
* Windows [![Build …
> Allow null arguments in the EventsExecutor parameters

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_event.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_event.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_features.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
> Allow null arguments in the EventsExecutor parameters (Humble backport)

- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
Fixes https://github.com/ros2/rclpy/issues/923.
Minimal code for reproducing error:
```python
import rclpy.serialization, std_msgs.msg
rclpy.serialization.deserialize_message(b"", std_msgs.msg.String)
```
Result without the fix:
```python
user@host:~$ python3
Python 3.8.10 (default, Sep 28 2021, 16:10:42) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rclpy.serialization, std_msgs.msg
>>> rclpy.serialization.deserialize_message(b"", std_msgs.msg.String)
terminate called after throwing an instance of 'eprosima::fastcdr::exception::NotEnoughMemoryException'
what():  Not enough memory in the buffer stream
Aborted (core dumped)
user@host:~$
```
Result with the fix:
```python
user@host:~$ python3
Python 3.8.10 (default, Sep 28 2021, …
```
> [Foxy] Handle exception on deserializing ROS message

- rmw_fastrtps_cpp/src/rmw_node.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/listener_thread.cpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
related https://ci.ros2.org/job/ci_linux-aarch64/11327/testReport/projectroot.test/rclcpp/test_publisher/.
```bash
[ERROR] [1653330857.635679668] [ns.my_node.rclcpp]: Error in destruction of rcl publisher handle: Failed to delete datawriter, at /home/jenkins-agent/workspace/ci_linux-aarch64/ws/src/ros2/rmw_fastrtps/rmw_fastrtps_shared_cpp/src/publisher.cpp:48, at /home/jenkins-agent/workspace/ci_linux-aarch64/ws/src/ros2/rcl/rcl/src/rcl/publisher.c:187
Failed to delete dds publisher from participantFailed to delete participant[       OK ] TestPublisher.intra_process_publish_failures (11 ms)
```
Signed-off-by: Tomoya.Fujita <Tomoya.Fujita@sony.com>
> add line feed for RCUTILS_SAFE_FWRITE_TO_STDERR

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
This should fix several issues related with services.
> Take all available samples on service/client on_data_available.

- rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
Listener callbacks for QoS events were being called when assigned.
They should be called here only if there were previous events before setting these callbacks.
This PR checks the `total_count_change` for each event, and if greater than zero, call the corresponding callback.
Signed-off-by: Mauro Passerino <mpasserino@irobot.com>
> Call callbacks only if unread count > 0

- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
Find duplicated code and remove it.
```c++
fastdds_wait_set->detach_condition(custom_event_info->get_listener()->get_statuscondition());
```
is the same as the following code
```c++
eprosima::fastdds::dds::StatusCondition & status_condition =
custom_event_info->get_listener()->get_statuscondition();
fastdds_wait_set->detach_condition(status_condition);
```
> Remove duplicated code

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
The only requirement on the Fast DDS API in order for loans to be used is that the type is plain.
This PR allows calling the loan APIs when data-sharing is OFF.
This enables performance improvements on intra-process and UDP.
> Allow loaned messages without data-sharing

- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
That way it is an actual C/C++ statement, and we can make minor changes to that macro as needed.
On its own, this isn't interesting, but I'm going to be doing some minor modifications to the `RMW_CHECK_TYPE_IDENTIFIERS_MATCH` macro that requires this.
> Make sure to add semicolons to the CHECK_TYPE_IDENTIFIER_MATCH.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
This should fix #646 by calling `get_unread_count` before taking the lock on the mutex `on_new_message_m_`.
It provides similar fixes for the callback setter on subscriptions, services, and clients.
> Delay lock on message callback setters

- README.md
When I try the talker/listener example in the README, I get the following error message.
```
$ FASTRTPS_DEFAULT_PROFILES_FILE=test.xml RMW_FASTRTPS_USE_QOS_FROM_XML=1 RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp talker
2023-01-24 11:18:49.428 [RTPS_READER_HISTORY Error] Change payload size of '60' bytes is larger than the history payload size of '35' bytes and cannot be resized. -> Function can_change_be_added_nts
2023-01-24 11:18:49.429 [RTPS_READER_HISTORY Error] Change payload size of '84' bytes is larger than the history payload size of '35' bytes and cannot be resized. -> Function can_change_be_added_nts
...
```
```
$ FASTRTPS_DEFAULT_PROFILES_FILE=test.xml RMW_FASTRTPS_USE_QOS_FROM_XML=1 RMW_IMPLEMENTATION=rmw_fastrtps_cpp ros2 run demo_nodes_cpp listener
2023-01-24 …
```
> Add "default subscriber profile" to the XML example in the README

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/publisher.hpp
- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/subscription.hpp
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/publisher.hpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/subscription.hpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_client_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/utils.hpp
- rmw_fastrtps_shared_cpp/src/publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
- rmw_fastrtps_shared_cpp/src/utils.cpp
Every DataReader and DataWriter in the system needs to have an associated Topic.  Ideally we would create these as one per publisher/subscriber, but Fast-DDS does not allow you to create multiple topics within the same DomainParticipant with the same topic name.  Instead, what we need to do is track ourselves whether a topic should be reused.
This was previously done with a combination of TopicHolder and cast_or_create_topic, but that had a couple of problems. First of all, a TopicHolder is really a SCOPE_EXIT by a different name.  Second, cast_or_create_topic worked, but really left the semantics of who owned a Topic up in the air.  If you created multiple topics with the same name, the first one would own it, and thus own the lifetime. The subsequent ones would reuse that.  But if you …
> Rewrite how Topics are tracked in rmw_fastrtps_cpp.

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/CMakeLists.txt
The main reason to do this is so that we can
compile rmw_fastrtps with the clang static analyzer. As of clang++-14 (what is in Ubuntu 22.04), the default still seems to be C++14, so we need to specify C++17 so that new things in the rclcpp headers work properly.
Further, due to reasons I don't fully understand, I needed to set CMAKE_CXX_STANDARD_REQUIRED in order for clang to really use that version. So set this as well.
> Update all rmw_fastrtps packages to C++17.

- rmw_fastrtps_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_dynamic_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/participant.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/utils/net_utils.hpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
- rmw_fastrtps_shared_cpp/src/rmw_init.cpp
- rmw_fastrtps_shared_cpp/src/utils/net_utils.cpp
Takes off from where #653 leaves off. Currently added support for IPv4 addresses as well as hostname based addressing.
Current status according to goal matrix (Ideal goal matrix can be found [here](https://discourse.ros.org/t/proposed-changes-to-how-ros-performs-discovery-of-nodes/27640), tools to compute the matrix can be found [here]()):
```
Other Host
static defined       static not defined
1      2      3      1      2      3      default      
static defined     1       ✓      ✓      ✓      ✗      ✗      ✓      ✗      
2       ✓      ✓      ✓      ✗      ✗      ✓      ✓      
3       ✓      ✓      ✓      ✗      ✗      ✓      ✓      
static not defined 1       ✗      ✗      ✗      ✗      ✗      ✗      ✗      
2       ✗      ✗      ✗      ✗      ✗      ✗      ✗      
3       ✓      ✗ …
```
> [WIP] Improve handling of dynamic discovery - rmw_fastrtps changes

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_publisher_info.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_subscriber_info.hpp
- rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_event.cpp
Implement the feature about ros2/rmw#330
> Implement matched event

- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/src/rmw_wait.cpp
This makes `rmw_wait` more aggressive about how it skips work.
In the case that a condition is already met, this will skip attaching/detaching conditions from the underlying waitset and skip waiting.
In the case that a wait is required, it generally looks like this: 
and when a wait isn't needed:
> Be more proactive about skipping work if possible

- rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
- rmw_fastrtps_shared_cpp/src/rmw_event.cpp
An alternative for #682 that should fix #681
> Fix matched event issues

- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Part of https://github.com/ros2/ros2_tracing/issues/18
Requires https://github.com/ros2/ros2_tracing/pull/56
Signed-off-by: Christophe Bedard <bedard.christophe@gmail.com>
> Use TRACETOOLS_ prefix for tracepoint-related macros

- rmw_fastrtps_shared_cpp/src/utils.cpp
The end stanza of create_datareader() is supposed to be attempting to create a datareader with the underlying Fast-DDS library.  If creation of the datareader returns a valid pointer, we've succeeded, and if it returns a nullptr, it has failed.
However, there were two separate problems of the logic checking for these conditions:
1. It was checking the datareader pointer-to-a-pointer, which should always be non-null.  What it really meant to check was the datareader pointer (dereferenced).
2. There is a fallback mechanism for when unique network flow endpoints were optionally required.  The problem with that is that when using the fallback, we never check again to make sure the fallback was successful.  Therefore, if we failed for another reason (like security), we would not discover it …
> Add in a missing data_reader check when creating subscription.

- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
Just trigger the `rmw_publish` tracepoint for loaned message publications too.
> Instrument loaned message publication code path

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
In particular, in the type-hash code we can handle a failure to encode or parse the type hash from the user data.  Once we've handled it, and printed out an error about it, we should clear it because we are going to continue on and something else down the line might have an error.
This will avoid errors like:
This error state is being overwritten:
<old message>
with this new error message:
<new message>
> Clear out errors once we have handled them.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
This PR enables using the XML profiles to set the maximum time to wait for the client response reader to be ready when sending a response from the service.
It will use the value from the `max_blocking_time`  tag, for which the default value is 100ms.
The following XML would set the timeout to 1 second for all services:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<dds xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
<profiles>
<publisher profile_name="service">
<qos>
<reliability>
<max_blocking_time>
<sec>1</sec>
</max_blocking_time>
</reliability>
</qos>
</publisher>
</profiles>
</dds>
```
> Use DataWriter Qos to configure max_blocking_time on rmw_send_response

- rmw_fastrtps_shared_cpp/src/custom_publisher_info.cpp
- rmw_fastrtps_shared_cpp/src/custom_subscriber_info.cpp
This is so that clang thread analysis works properly.
This goes along with https://github.com/ros2/rcpputils/pull/180
> Switch to using rclcpp::unique_lock.

- rmw_fastrtps_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_dynamic_cpp/src/init_rmw_context_impl.cpp
Using a unique listening port for `ros_discovery_info` will make that topic have its own socket buffer, thus avoiding interference from other topics.
This could help mitigate service discovery issues when incoming network traffic on user topics is high.
> Improve node graph delivery by using a unique listening port

- rmw_fastrtps_cpp/src/rmw_count.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_count.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
- rmw_fastrtps_shared_cpp/src/rmw_count.cpp
this PR is for service counts using it's name like topic.
Related to https://github.com/ros2/ros2cli/pull/771
Signed-off-by: leeminju531 <dlalswn531@naver.com>
> Add rmw_count clients,services impl

- rmw_fastrtps_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/init_rmw_context_impl.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_subscription.cpp
- rmw_fastrtps_shared_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
- rmw_fastrtps_shared_cpp/src/rmw_publisher.cpp
- rmw_fastrtps_shared_cpp/src/rmw_service.cpp
- rmw_fastrtps_shared_cpp/src/rmw_subscription.cpp
to address one warning TSAN about `lock-order-inversion` mentioned at https://github.com/ros2/ros2/issues/1488#issuecomment-1752278901.
<details><summary> TSAN warning log </summary>
<p>
```shell
WARNING: ThreadSanitizer: lock-order-inversion (potential deadlock) (pid=1926091)
Cycle in lock order graph: M254870179752816080 (0x000000000000) => M277106926251347976 (0x000000000000) => M254870179752816080
Mutex M277106926251347976 acquired here while holding mutex M254870179752816080 in main thread:
#0 pthread_mutex_lock ../../../../src/libsanitizer/sanitizer_common/sanitizer_common_interceptors.inc:4240 (libtsan.so.0+0x53908)
#1 __gthread_mutex_lock /usr/include/x86_64-linux-gnu/c++/11/bits/gthr-default.h:749 (librmw_fastrtps_cpp.so+0x2669e)
#2 std::mutex::lock() …
```
> avoid using dds common public mutex directly

- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
In particular, when building in release mode the assert is compiled out, so 'identifier' is never used.  Just quiet this warning.
> Quiet compiler warning in Release mode.

- rmw_fastrtps_cpp/CMakeLists.txt
- rmw_fastrtps_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/src/rmw_dynamic_message_type_support.cpp
- rmw_fastrtps_shared_cpp/CMakeLists.txt
- rmw_fastrtps_shared_cpp/package.xml
- rmw_fastrtps_shared_cpp/test/CMakeLists.txt
This allows us to make more of our dependencies PRIVATE.
> Switch to target_link_libraries for linking.

- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/include/rmw_fastrtps_dynamic_cpp/TypeSupport_impl.hpp
This should fix crashes coming from serialization mismatches that cannot be detected by Fast CDR
Related to https://github.com/ros2/ros2_documentation/issues/3288#issuecomment-1404876431
> Capture `std::bad_alloc` on deserializeROSmessage.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/rmw_common.hpp
Kind of a silly change, but just make sure to use Unix line endings in rmw_common.hpp, which matches all of the rest of the files in this repository.  There is no functional change in this PR.
> Switch to Unix line endings.

- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
Depends on https://github.com/ros2/ros2_tracing/pull/74
For some background: https://github.com/ros2/ros2_tracing/issues/73
Question: Has `write_w_timestamp` + `Time_t::now` any drawbacks if compared with using plain `write`?
> Add timestamp to rmw_publish tracepoint

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_service_info.hpp
We can just use brace initialization here, and this allows us to side-step an uncrustify issue with the constructor.
> Remove an unnecessary constructor.

- README.md
follow-up https://discourse.ros.org/t/ros-2-and-large-data-transfer-on-lossy-networks/36598
> add FASTDDS_BUILTIN_TRANSPORTS env value doc.

- rmw_fastrtps_shared_cpp/src/rmw_publish.cpp
- rmw_fastrtps_shared_cpp/src/rmw_take.cpp
Please, refer to https://github.com/ros2/rclcpp/pull/2448 .
I have added the following trace points.
- `__rmw_publish_serialized_message()` 
- tracepoint : rmw_publish
- `_take_serialized_message()`
- tracepoint : rmw_take
> Add tracepoint for publish/subscribe serialized_message

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
- rmw_fastrtps_shared_cpp/src/qos.cpp
- rmw_fastrtps_shared_cpp/test/test_rmw_qos_to_dds_attributes.cpp
This fixes the failures mentioned [here](https://github.com/ros2/ros2/pull/1560#issue-2286372464) by implementing the new `is_plain` overload of Fast DDS type support interface.
It additionally sets the data representation policy of created DataReader and DataWriter entities to XCDR1, since it is what the type support is using.
> Add support for data representation

- rmw_fastrtps_shared_cpp/src/utils.cpp
This PR makes every Content Filter Name unique by adding a static atomic counter. With this change, two or more content-filtered subscriptions can be created for the same topic name.
Tests are included in the following related PRs
* https://github.com/ros2/rclcpp/pull/2546
* https://github.com/ros2/rmw_implementation/pull/230
> Use unique mangled names when creating Content Filter Topics

- rmw_fastrtps_shared_cpp/src/rmw_wait_set.cpp
https://github.com/ros2/rmw/pull/275 changed the `rmw_destroy_wait_set()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `wait_set` is `NULL`. However, this wasn't the case in practice in the implementations of `rmw_destroy_wait_set()` or in the relevant test.
Change the implementation here to return `RMW_RET_INVALID_ARGUMENT`.
Requires https://github.com/ros2/rmw_implementation/pull/234
> Make rmw_destroy_wait_set return RMW_RET_INVALID_ARGUMENT

- rmw_fastrtps_shared_cpp/src/rmw_node.cpp
`rmw_namespace_validation_result_string()` -- not `rmw_node_name_validation_result_string()` -- should be called with the validation result from `rmw_validate_namespace()`.
In practice, this meant that the reason given might have been `"unknown result code for rmw node name validation"` given that `rmw_node_name_validation_result_string()` doesn't know about all validation results from `rmw_validate_namespace()`. However, we don't test error messages anywhere and rarely rely on them, so it doesn't/shouldn't affect any tests or functionality.
Related PRs:
* https://github.com/ros2/rmw_cyclonedds/pull/497
* https://github.com/ros2/rmw_connextdds/pull/151
* https://github.com/ros2/rmw_zenoh/pull/196
> Use rmw_namespace_validation_result_string() in rmw_create_node

- rmw_fastrtps_shared_cpp/src/rmw_service_server_is_available.cpp
https://github.com/ros2/rmw/pull/277 changed the `rmw_service_server_is_available()` API documentation to indicate that it returns `RMW_RET_INVALID_ARGUMENT` if `node`, `client`, or `is_available` are `NULL`. However, this wasn't the case in practice in the implementations of `rmw_service_server_is_available()` or in the relevant test.
Change the implementation here to return `RMW_RET_INVALID_ARGUMENT`.
Requires https://github.com/ros2/rmw_implementation/pull/231
> Make rmw_service_server_is_available return RMW_RET_INVALID_ARGUMENT

- rmw_fastrtps_dynamic_cpp/CMakeLists.txt
- rmw_fastrtps_dynamic_cpp/package.xml
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
`rmw_fastrtps_cpp` is already instrumented. Since some of the tracing instrumentation is in `rmw_fastrtps_shared_cpp` (thus covering both `rmw_fastrtps_cpp` and `rmw_fastrtps_dynamic_cpp`), instrumenting `rmw_fastrtps_dynamic_cpp` is rather simple.
Part of https://github.com/ros2/ros2_tracing/pull/127
> Add tracing instrumentation to rmw_fastrtps_dynamic_cpp

- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
part of https://github.com/ros2/rmw/issues/357
> Unique Client GID for Service Introspectino Event.

- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
This reverts commit 565bbc22357413aa7342e9dd0d6518b71f7f10a6.
We believe this PR might be related to some consistent hangs we have found in the rhel buildfarm jobs, we will try to reproduce before considering to merge this PR.
> Revert "Unique Client GID for Service Introspectino Event. (#779)"

- rmw_fastrtps_shared_cpp/src/rmw_get_gid_for_client.cpp
part of https://github.com/ros2/rmw/issues/357
> Use client's reader guid for service introspection event gid.

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_participant_info.hpp
- rmw_fastrtps_shared_cpp/src/participant.cpp
We've seen several issues related with destruction order lately.
This PR aims to mitigate them by leveraging Fast DDS `DomainParticipantFactory::get_shared_instance()`.
It should then avoid the automatic destruction of the factory (and the participants it created) until all the contexts in the process have been destroyed.
This can be backported to Jazzy and Iron, but not Humble, since `get_shared_instance()` is only available from Fast DDS 2.8.0 onwards.
> Keep reference to `DomainParticipantFactory`

- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
See https://github.com/ros2/rosidl_dynamic_typesupport/issues/11 for a description on why we want to do this.
> Drop support for float128.

- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_shared_cpp/src/rmw_request.cpp
- rmw_fastrtps_shared_cpp/src/rmw_response.cpp
This adds instrumentation to clients and services using `tracetools` for end-to-end tracking of requests/responses. For more information, see https://github.com/ros2/ros2_tracing/pull/145.
Requires https://github.com/ros2/ros2_tracing/pull/145
> Instrument client/service for end-to-end request/response tracking

- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/custom_event_info.hpp
depends on https://github.com/ros2/rmw/pull/380
> introduce RMW_EVENT_TYPE_MAX in rmw_event_type_t.

- rmw_fastrtps_cpp/include/rmw_fastrtps_cpp/TypeSupport.hpp
- rmw_fastrtps_cpp/src/publisher.cpp
- rmw_fastrtps_cpp/src/rmw_client.cpp
- rmw_fastrtps_cpp/src/rmw_service.cpp
- rmw_fastrtps_cpp/src/subscription.cpp
- rmw_fastrtps_cpp/src/type_support_common.cpp
- rmw_fastrtps_dynamic_cpp/src/MessageTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/ServiceTypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/TypeSupport.hpp
- rmw_fastrtps_dynamic_cpp/src/TypeSupport_impl.hpp
- rmw_fastrtps_dynamic_cpp/src/publisher.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_client.cpp
- rmw_fastrtps_dynamic_cpp/src/rmw_service.cpp
- rmw_fastrtps_dynamic_cpp/src/subscription.cpp
- rmw_fastrtps_dynamic_cpp/src/type_support_proxy.cpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/TypeSupport.hpp
- rmw_fastrtps_shared_cpp/include/rmw_fastrtps_shared_cpp/utils.hpp
- rmw_fastrtps_shared_cpp/src/TypeSupport_impl.cpp
- rmw_fastrtps_shared_cpp/src/utils.cpp
This PR adds the necessary code to support topic instances in `rmw_fastrtps_cpp` and `rmw_fastrtps_dynamic_cpp`
* Part of ros2/ros2#1538:
* Depends on ros2/rosidl#796
* Depends on ros2/rosidl_typesupport_fastrtps#116
> Support topic instances
